### ISSUE TITLE
Access to error list strings from each field

### ISSUE THREAD

**Issue by robertoltrocha** [flutter-form-builder-ecosystem/flutter_form_builder#1014]
Hi,
How can I get a list of text errors from all fields when submit and the form is not valid? I would like to show theses errors in another widget or format.

```
 void savePressed() async {
    final form = _formKey.currentState;
    if (form!.validate()) {
      form.save();     
    } else {
      **// HERE I WOULD LIKE TO HAVE ACCESS TO THE ERROR LIST**

    }
  }
```

**Comment by mdfaraz** [comment]
@deandreamatias 

You can access the error list through fields:
`_formKey.currentState?.fields.values.where((element) => element.hasError).toList()`

**Comment by mdfaraz** [comment]
@robertoltrocha 

Try this to get the error list:
`_formKey.currentState?.fields.values.where((element) => element.hasError).toList().map((e) => e.errorText).toList();`

**Comment by deandreamatias** [comment]
Can test this on [pre-release 9.0.0-dev.1](https://pub.dev/packages/flutter_form_builder/versions/9.0.0-dev.1)
