### ISSUE TITLE
[Request] Add Example Screenshots

### ISSUE THREAD

**Issue by Mugilan-Codes** [flutter-form-builder-ecosystem/flutter_form_builder#1027]
# Example Screenshots

## Please add Example screenshots or gifs or videos

**Comment by WilliamCunhaCardoso** [comment]
That is an interesting issue. @danvick I believe it would be good to reformulate the readme. Dividing it in sections and redirections to other pages, for example, the screenshot ones.

How can we discuss about it?

**Comment by Mugilan-Codes** [comment]
I will be happy to help you with this issue

Just let me know How can I help with this

**Comment by WilliamCunhaCardoso** [comment]
> I will be happy to help you with this issue
> 
> Just let me know How can I help with this

Awesome <3. Let's wait from package owner since it is related to structure. My opinion is dividing in sections, then having a specific section for examples. But first we must check with the owner to have directions.

**Comment by deandreamatias** [comment]
Can test this on [pre-release 9.0.0-dev.1](https://pub.dev/packages/flutter_form_builder/versions/9.0.0-dev.1)
