### ISSUE TITLE
[Request] Updated Geo/Map picker

### ISSUE THREAD

**Issue by anqit** [flutter-form-builder-ecosystem/flutter_form_builder#1030]
Since it seems https://pub.dev/packages/form_builder_map_field is no longer maintained, is there an alternative to getting this functionality? Or any plans to revive this project or add a map picker to `flutter_form_builder` itself?

Would be super helpful, and a great addition to an already fantastic library!

**Comment by WilliamCunhaCardoso** [comment]
An alternative way is to build a custom field with `FormBuilderField`. But, I believe or update or deprecating the external package should be the more adequate approach.

**Comment by danvick** [comment]
I will try to have the package up to date as soon as I can.

The array of packages for me to maintain may have outgrown me, especially given my limited availability of late.

I very much appreciate the help of my co-maintainers @awhitford, @WilliamCunhaCardoso, and @deandreamatias and welcome even more support.

I'm also planning to bring other related packages into this repo and have them all here, which will make them easier to maintain.

**Comment by deandreamatias** [comment]
This package currently is archived by reasons that I explain in the readme
