### ISSUE TITLE
FormBuilderSwitch validation error message not disappearing even the right action has been taken by user

### ISSUE THREAD

**Issue by agustin-garcia** [flutter-form-builder-ecosystem/flutter_form_builder#1072]
## Environment

**Package name:**  

## Describe your question

FormBuilderSwitch validation error message should dissapear after User select but such error message doesn't hide as expected

![image](https://user-images.githubusercontent.com/3145497/177362617-37eb78f4-f23e-4d31-91be-62a7201ce5b2.png)

I tried options from different forums, but I'm unable to make it work. Could you please provide an example?
Thanks

**Comment by deandreamatias** [comment]
Hi @agustin-garcia 
Can provider a code sample of this image?
Thanks

**Comment by deandreamatias** [comment]
Due to lack of response, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/new/choose)
