### ISSUE TITLE
FormBuilderDateTimePicker reset button missing / not functioning

### ISSUE THREAD

**Issue by codeforhome** [flutter-form-builder-ecosystem/flutter_form_builder#1077]
## Environment

**Package name and version:**  

<details>
  <summary>Flutter doctor</summary>

[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Version 10.0.22000.739], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.68.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.

</details>

<details>

```dart
    FormBuilderDateTimePicker(
        name: 'expiredDate',
        inputType: InputType.date,
    ),
```

</details>

## Description

**Expected behavior:** 
click the reset button to return to initial value

**Current behavior:**
button missing/ not functioning

## Steps to reproduce

1. Just run the package example in [flutter_form_builder](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder)/[packages](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/tree/master/packages)/[flutter_form_builder](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/tree/master/packages/flutter_form_builder)/example/

**Comment by tonypottera24** [comment]
same issue

**Comment by ian-ng** [comment]
Can set null to `FormBuilderDateTimePicker.resetIcon`, and set a `IconButton` to `FormBuilderDateTimePicker.decoration.suffix` as a hot-fix.
The `IconButton.onPressed` can refer to #859.

**Comment by deandreamatias** [comment]
This icon never was functionality. Only was a decorative icon.
I will remove in #1094.
If need implement a reset button, please use a decoration.suffix to do this
