### ISSUE TITLE
FormBuilderDropdown reset button wrong color

### ISSUE THREAD

**Issue by tonypottera24** [flutter-form-builder-ecosystem/flutter_form_builder#1078]
The color of the reset button in `FormBuilderDropdown` is `black`.
In other widgets, the reset button looks like `black54`.
The color cannot be changed by `InputDecoration.suffixIconColor`.

**Comment by deandreamatias** [comment]
Hi @tonypottera24 
With reset button do you refer to `resetIcon`?

**Comment by tonypottera24** [comment]
Hi @deandreamatias 
yes... but I just noticed that it is called `cleanIcon` here...
and I cannot set it to null and provide my own icon by `suffixIcon`.

**Comment by deandreamatias** [comment]
Yeah yeah, I misstype my sentence

**Comment by tonypottera24** [comment]
@deandreamatias sorry that I'm not blaming you.
I'm just expect that `FormBuilder` ecosystem should use the same terms.
