### ISSUE TITLE
FormBuilderDropdown change location items

### ISSUE THREAD

**Issue by lllymaknuga** [flutter-form-builder-ecosystem/flutter_form_builder#1082]
## Environment

**Package name:**  
Everyone Hi
I want the item select sheet to always be strictly FormBuilderDropdown
How to do it?

**Comment by lllymaknuga** [comment]
FormBuilderDropdown(
              elevation: 1,
              name: 'city_dropdown',
              initialValue: 'Нур-Султан',
              items: const [
                DropdownMenuItem(
                  value: 'Алматы',
                  child: Text('Алматы'),
                ),
                DropdownMenuItem(
                  value: 'Москва',
                  child: Text('Москва'),
                ),
                DropdownMenuItem(
                  value: 'Питер',
                  child: Text('Питер'),
                ),
                DropdownMenuItem(
                  value: 'Нур-Султан',
                  child: Text('Нур-Султан'),
                ),
              ],)
I have written like this

**Comment by deandreamatias** [comment]
> ![Снимок экрана 2022-07-12 в 18 58 10](https://user-images.githubusercontent.com/74775396/178507652-284dc633-f148-4bb6-bb58-185332e61f19.png) I want do this

I don't know what means _this_
A round component, a custom icon, a line between options...

Need more details that expect behaviour and actual behaviour

**Comment by lllymaknuga** [comment]
If you look at the picture, you can see that the list for selecting cities is located under the FormBuilderDropdown.
How to do also?

**Comment by deandreamatias** [comment]
> I have written like this `FormBuilderDropdown( elevation: 1, name: 'city_dropdown', initialValue: 'Нур-Султан', items: const [ DropdownMenuItem( value: 'Алматы', child: Text('Алматы'), ), DropdownMenuItem( value: 'Москва', child: Text('Москва'), ), DropdownMenuItem( value: 'Питер', child: Text('Питер'), ), DropdownMenuItem( value: 'Нур-Султан', child: Text('Нур-Султан'), ), ], )`

I can see the list, but this code don't is enough for that?

**Comment by lllymaknuga** [comment]
No)
If i tap on FormBuilderDropdown his list went down from below him.
From this it looks like this
![image](https://user-images.githubusercontent.com/74775396/178828080-58b8e60a-1615-4a94-b7da-1ac90c2a668c.png)
![image](https://user-images.githubusercontent.com/74775396/178828129-3aed7977-741c-434a-8176-d59ff3fa9e0c.png)

**Comment by deandreamatias** [comment]
Do you want that dropdown options appers below of FormBuilderDropdownField?

![178828080-58b8e60a-1615-4a94-b7da-1ac90c2a668c](https://user-images.githubusercontent.com/21011641/178980106-bd2a9b99-2bf2-4071-8423-eef6fcc724fc.png)

**Comment by deandreamatias** [comment]
Due to lack of response, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/new/choose)
