### ISSUE TITLE
How i can show owner custom date picker if tap on FormBuilderDateTimePicker

### ISSUE THREAD

**Issue by lllymaknuga** [flutter-form-builder-ecosystem/flutter_form_builder#1085]
How i can show owner date picker
![image](https://user-images.githubusercontent.com/74775396/178805026-d23f79e7-52a8-4a6a-a896-c57161e5eaa1.png)
FormBuilderDateTimePicker if i tap date picker looks like this(from box)
I want if i tap on FormBuilderDateTimePicker show my date picker
![image](https://user-images.githubusercontent.com/74775396/178805364-e7a3113f-1830-4316-9e6d-6554306583eb.png)

How i can do this?

**Comment by deandreamatias** [comment]
No, actually this package don't has support to this.
form builder only use native cupertino and material components

**Comment by lllymaknuga** [comment]
Okay
Thank you for your answer answer
