### ISSUE TITLE
A value of type 'FormBuilderFieldOption<String>' can't be assigned to a variable of type 'FormBuilderChipOption<String>'.

### ISSUE THREAD

**Issue by Isaachm11** [flutter-form-builder-ecosystem/flutter_form_builder#1087]
## The following is the error
Error: A value of type 'FormBuilderFieldOption<String>' can't be assigned to a variable of type 'FormBuilderChipOption<String>'.
     - 'FormBuilderFieldOption' is from 'package:flutter_form_builder/src/form_builder_field_option.dart' ('../programs/flutter_3_0_4/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-7.4.0/lib/src/form_builder_field_option.dart').
     - 'FormBuilderChipOption' is from 'package:flutter_form_builder/src/options/form_builder_chip_option.dart' ('../programs/flutter_3_0_4/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-7.4.0/lib/src/options/form_builder_chip_option.dart').
            FormBuilderFieldOption(value: '5', child: Text('Excelent')),

This happens on all the FormBuilderFieldOption inside the FormBuilderChipOption options

## The following is the code I'm using
FormBuilderChoiceChip<String> _choiceChipRateService() {
    return FormBuilderChoiceChip(
      name: 'rate',
      alignment: WrapAlignment.spaceEvenly,
      validator:
          FormBuilderValidators.required(errorText: "Please select one"),
      selectedColor: Color.fromARGB(255, 147, 209, 235),
      decoration: InputDecoration(
        labelText: 'Select how was the service',
        labelStyle: TextStyle(
          color: Color.fromARGB(255, 25, 101, 108),
        ),
        border: InputBorder.none,
      ),
      options: [
        FormBuilderFieldOption(value: '1', child: Text('Very bad')),
        FormBuilderFieldOption(
            value: '2', child: Text('Bad')),
        FormBuilderFieldOption(value: '3', child: Text('Regular')),
        FormBuilderFieldOption(value: '4', child: Text('Good')),
        FormBuilderFieldOption(value: '5', child: Text('Very good')),
        FormBuilderFieldOption(value: '6', child: Text('Excelent')),
      ],
    );
  }

Please help on how to fix this

**Comment by Isaachm11** [comment]
This happens when building for ios

**Comment by deandreamatias** [comment]
Please complete the issue template to can help you

## Environment

**Package version:**

<details>
  <summary>Flutter doctor</summary>


```
```

</details>

<details>
  <summary>Code sample</summary>



```dart
```

</details>

## Description

**Expected behavior:**

**Current behavior:**

## Steps to reproduce

1. This
2. Than that
3. Then

## Images   

## Stacktrace/Logcat

**Comment by Isaachm11** [comment]
That issue was solved, I have another issue:


    ../programs/flutter_3_0_4/.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.10.0/lib/src/chips_input.dart:87:7: Error: The non-abstract class 'ChipsInputState' is missing implementations for these members:
     - TextInputClient.insertTextPlaceholder
     - TextInputClient.removeTextPlaceholder
     - TextInputClient.showToolbar
    Try to either
     - provide an implementation,
     - inherit an implementation from a superclass or mixin,
     - mark the class as abstract, or
     - provide a 'noSuchMethod' implementation.

    class ChipsInputState<T> extends State<ChipsInput<T>>
          ^^^^^^^^^^^^^^^
    ../programs/flutter_3_0_4/packages/flutter/lib/src/services/text_input.dart:1124:8: Context: 'TextInputClient.insertTextPlaceholder' is defined here.
      void insertTextPlaceholder(Size size) {}
           ^^^^^^^^^^^^^^^^^^^^^
    ../programs/flutter_3_0_4/packages/flutter/lib/src/services/text_input.dart:1127:8: Context: 'TextInputClient.removeTextPlaceholder' is defined here.
      void removeTextPlaceholder() {}
           ^^^^^^^^^^^^^^^^^^^^^
    ../programs/flutter_3_0_4/packages/flutter/lib/src/services/text_input.dart:1116:8: Context: 'TextInputClient.showToolbar' is defined here.
      void showToolbar() {}
           ^^^^^^^^^^^

**Comment by deandreamatias** [comment]
Please open a new issue with details in template
