### ISSUE TITLE
FormBuilderRadioGroup initialValue not working

### ISSUE THREAD

**Issue by halloway** [flutter-form-builder-ecosystem/flutter_form_builder#1099]
## Environment

**Package version:** 7.5.0

## Describe your question
I was wondering how to define the initialValue when using a FormBuilderRadioGroup as it does not seem to work for me.

```
FormBuilderRadioGroup<String>(
                    decoration: const InputDecoration(
                      labelText: 'My chosen language',
                    ),
                    initialValue: 'Dart',
                    name: 'best_language',
                    activeColor: Colors.green,
                    onChanged: _onChanged,
                    validator: FormBuilderValidators.compose(
                        [FormBuilderValidators.required()]),
                    options: ['Dart', 'Kotlin', 'Java', 'Swift', 'Objective-C']
                        .map((lang) => FormBuilderFieldOption(
                              value: lang,
                              child: Text(lang),
                            ))
                        .toList(growable: false),
                  ),
```

I would expect that Dart is already preselected but it is not.

<img width="283" alt="image" src="https://user-images.githubusercontent.com/24854934/182029575-f9879547-388d-4bd8-bf99-7846160b258c.png">

Once I selected an option it is highlighted as expected.

<img width="283" alt="image" src="https://user-images.githubusercontent.com/24854934/182029630-b65b677f-85b6-4e0e-a01e-613c38711b12.png">

**Comment by deandreamatias** [comment]
Hi @halloway! Thanks for your question
This is more like a bug instead question, but ok.

Do you try set a initial value by FormBuilder?

**Comment by halloway** [comment]
Weird.
Simply adding a name value to the FormBuilderRadioGroup fixed the issue and the initialValue works.
Good to know.
Thanks

**Comment by Shahmirzali-Huseynov** [comment]
@halloway  can you explain with the code? because you set the name value before. how solved the problem?

**Comment by halloway** [comment]
> @halloway can you explain with the code? because you set the name value before. how solved the problem?

In my original code I missed it out.
