### ISSUE TITLE
7.4.0 has breaking change

### ISSUE THREAD

**Issue by carlleeswanson** [flutter-form-builder-ecosystem/flutter_form_builder#1100]
### Describe the change you would like to see
The "Changelog" on pub.dev for version 7.4.0 should indicate that there is a breaking change: it now requires Flutter SDK v3.0 or greater.
I think that the "Versions" info on pub.dev for version 7.4.0 should also indicate minimum Dart SDK v2.17

### How would the suggested change make the documentation more useful?
It is hard to know which versions of the package to install without this info on the underlying support requirements. I had to do trial-and-error to go back to a version that actually worked with my environment (Flutter 2.10.5)

**Comment by deandreamatias** [comment]
Hi @carlleeswanson 
Yeah, I know that. Unfortunately, the changelog don't show the breaking change that should.
In [this thread](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/1028#issuecomment-1135848844), can see that in 7.3.0 has introduced a breaking change: If not use Flutter 3.0.0, the app crash.
In version 7.4.0 I specify the minimal versions to avoid this errors on future.

Maybe I can add this info on changelog, even if it is a posteriori

**Comment by deandreamatias** [comment]
Can close this issue or you need some change?

**Comment by carlleeswanson** [comment]
Thank you for clarifying/confirming!
