### ISSUE TITLE
FormBuilderDateRangePickerState deprecated

### ISSUE THREAD

**Issue by jmpavan** [flutter-form-builder-ecosystem/flutter_form_builder#1102]
## Environment

**Package version:**
7.5.0

## Describe your question
I have a working form in Flutter with version 7.2.1 and FormBuilderDateRangePickerState but in 7.5.0 it doesn't exist anymore.  How should I do the replacement?  Thanks.

**Comment by deandreamatias** [comment]
Hi!
This code still in package but is private because is a state for `FormBuilderDateRangePicker`. Do you need for something specific? You can access to some methods by `formKey.currentState.fields['field_name']`

**Comment by jmpavan** [comment]
Matias: I replace a declaración

*GlobalKey<FormBuilderDateRangePickerState>()*

by

*GlobalKey<FormBuilderFieldState>()*

and it work.

Thanks!

Jorge Mario Paván
+54 9 11 5327 9247
***@***.***
