### ISSUE TITLE
update product work in fine,but in edit product the initial values not update correctly | Flutter Form Builder

### ISSUE THREAD

**Issue by TOMER628** [flutter-form-builder-ecosystem/flutter_form_builder#1110]
when i update values in existing Product thats work fine and that show up also in Shop navigator.

But when i edit same product again the Initial Values is remember old values.

**Screenshot :**

**Original Product**
[https://img-c.udemycdn.com/redactor/raw/q_and_a/2022-09-06_14-22-10-463c86e33869350cf12d6b64461561c2.PNG](url)

**Title edited and show the changed** 
[https://img-c.udemycdn.com/redactor/raw/q_and_a/2022-09-06_14-22-10-a268e501496a6fb362bfb229e4035c3d.PNG](url)

Edit again same Product ,but initial value of title not correct :
[https://img-c.udemycdn.com/redactor/raw/q_and_a/2022-09-06_14-22-10-9408fb703d1fe0b84587d9b5c7e8c17f.PNG](url)

the code is:
`import 'package:flutter/material.dart';
import '../provider/products_provider.dart';
import 'package:provider/provider.dart';
import '../provider/product.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';
import 'package:form_builder_validators/form_builder_validators.dart';
 
class EditProductScreen extends StatefulWidget {
  const EditProductScreen({Key? key}) : super(key: key);
  static const routhName = 'edit-product';
 
  @override
  State<EditProductScreen> createState() => _EditProductScreenState();
}
 
class _EditProductScreenState extends State<EditProductScreen> {
  final _priceFocus = FocusNode();
  final _descriptionFocusNode = FocusNode();
  final _imageUrlController = TextEditingController();
  final _imageUrlFocusNode = FocusNode();
  final _formKey = GlobalKey<FormBuilderState>();
  final _keyValidate = GlobalKey<FormBuilderFieldState>();
  Map<String, dynamic> _initialValues = {
    'title': '',
    'price': '',
    'description': '',
    'urlImage': '',
  };
 
  var _newProduct = Product(
    id: null.toString(),
    title: '',
    description: '',
    price: 0,
    imageUrl: '',
  );
 
 var _isInit = true;
 
  @override
  void didChangeDependencies() {
    if (_isInit) {
      if (ModalRoute.of(context)!.settings.arguments != null) {
        final idProduct = ModalRoute.of(context)?.settings.arguments as String;      
        _newProduct = ProductsProvider().findByID(idProduct);        
        _initialValues = {
          'id': _newProduct.id,
          'title': _newProduct.title,
          'price': _newProduct.price.toString(),
          'description': _newProduct.description,
          'urlImage': _newProduct.imageUrl,
        };
        print('initialValues: $_initialValues');
      } else {
        _initialValues = _initialValues;
      }
    }
    _isInit = false;
    super.didChangeDependencies();
  }
 
  @override
  void initState() {
    _imageUrlFocusNode.addListener(_updateScope);
 
    super.initState();
  }
 
  void _updateScope() {
    if (!_imageUrlFocusNode.hasFocus) {
      setState(() {});
    }
  }
 
  void _saveForm() {
    _formKey.currentState!.validate();
    _formKey.currentState!.save();
    if (_newProduct.id != null.toString()) {
      Provider.of<ProductsProvider>(context, listen: false)
          .updateProduct(_newProduct.id, _newProduct);
      
    } else {
      Provider.of<ProductsProvider>(context, listen: false)
          .addProduct(_newProduct);
      
    }
    Navigator.of(context).pop();
  }
 
  @override
  void dispose() {
    _priceFocus.dispose();
    _descriptionFocusNode.dispose();
    _imageUrlController.dispose();
    _imageUrlFocusNode.removeListener(_updateScope);
    super.dispose();
  }
 
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Product Editor'),
        actions: [
          IconButton(
            onPressed: _saveForm,
            icon: const Icon(Icons.save),
          ),
        ],
      ),
      body: ListView(
        padding: const EdgeInsets.all(12),
        children: [
          FormBuilder(
            initialValue: _initialValues,
            key: _formKey,
            child: Column(
              children: [
                FormBuilderTextField(
                  name: 'title',
                  keyboardType: TextInputType.text,
                  decoration: InputDecoration(
                    border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(8)),
                    label: const Text('Title:'),
                    hintText: 'Entet Title of product',
                    labelStyle:
                        TextStyle(color: Theme.of(context).colorScheme.primary),
                  ),
                  validator: FormBuilderValidators.compose([
                    FormBuilderValidators.required(
                        errorText: 'cannot be an EMPTY'),
                    FormBuilderValidators.minLength(2,
                        errorText: '2 Charartes Minimum'),
                  ]),
                  textInputAction: TextInputAction.next,
                  onSubmitted: (value) =>
                      FocusScope.of(context).requestFocus(_priceFocus),
                  onSaved: (newValue) {
                    _newProduct = Product(
                      id: _newProduct.id,
                      title: _formKey.currentState!.fields['title']?.value,
                      description: _newProduct.description,
                      price: _newProduct.price,
                      imageUrl: _newProduct.imageUrl,
                      isFavorite: _newProduct.isFavorite,
                    );
                  },
                ),
                SizedBox(height: 15),
                FormBuilderTextField(
                  autovalidateMode: AutovalidateMode.onUserInteraction,
                  name: 'price',
                  decoration: InputDecoration(
                    border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(8)),
                    label: const Text('Price:'),
                    hintText: 'Entet Price of product',
                    labelStyle:
                        TextStyle(color: Theme.of(context).colorScheme.primary),
                  ),
                  keyboardType:
                      const TextInputType.numberWithOptions(decimal: true),
                  textInputAction: TextInputAction.next,
                  onSubmitted: (value) => FocusScope.of(context)
                      .requestFocus(_descriptionFocusNode),
                  focusNode: _priceFocus,
                  validator: FormBuilderValidators.compose([
                    FormBuilderValidators.required(
                        errorText: 'cannot be an EMPTY'),
                    FormBuilderValidators.numeric(
                        errorText: 'only Numbers allowed'),
                    FormBuilderValidators.min(
                      0,
                      errorText: 'positive only',
                    ),
                  ]),
                  onSaved: (newValue) {
                    _newProduct = Product(
                      id: _newProduct.id,
                      title: _newProduct.title,
                      description: _newProduct.description,
                      price: double.parse(
                          _formKey.currentState!.fields['price']?.value),
                      imageUrl: _newProduct.imageUrl,
                      isFavorite: _newProduct.isFavorite,
                    );
                  },
                ),
                SizedBox(height: 15),
                FormBuilderTextField(
                    autovalidateMode: AutovalidateMode.onUserInteraction,
                    name: 'description',
                    decoration: InputDecoration(
                      border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8)),
                      label: const Text('Description:'),
                      hintText: 'Entet Description',
                      labelStyle: TextStyle(
                          color: Theme.of(context).colorScheme.primary),
                    ),
                    keyboardType: TextInputType.text,
                    onSubmitted: (value) =>
                        FocusScope.of(context).requestFocus(_imageUrlFocusNode),
                    focusNode: _descriptionFocusNode,
                    validator: FormBuilderValidators.compose([
                      FormBuilderValidators.required(
                          errorText: 'cannot be an EMPTY'),
                      FormBuilderValidators.minLength(
                        8,
                        errorText: '8 Chartartes minimum',
                      ),
                    ]),
                    textInputAction: TextInputAction.next,
                    onSaved: (newValue) {
                      _newProduct = Product(
                        id: _newProduct.id,
                        title: _newProduct.title,
                        description:
                            _formKey.currentState!.fields['description']?.value,
                        price: _newProduct.price,
                        imageUrl: _newProduct.imageUrl,
                        isFavorite: _newProduct.isFavorite,
                      );
                    }),
                SizedBox(height: 15),
                FormBuilderTextField(
                    autovalidateMode: AutovalidateMode.onUserInteraction,
                    name: 'urlImage',
                    decoration: InputDecoration(
                      border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8)),
                      label: const Text('Url Image:'),
                      hintText: 'Entet address Url Image',
                      labelStyle: TextStyle(
                          color: Theme.of(context).colorScheme.primary),
                    ),
                    keyboardType: TextInputType.url,
                    onSubmitted: (value) =>
                        _keyValidate.currentState!.requestFocus(),
                    focusNode: _imageUrlFocusNode,
                    validator: FormBuilderValidators.compose([
                      FormBuilderValidators.required(
                          errorText: 'cannot be empty'),
                      FormBuilderValidators.url(errorText: 'Enter valid Url'),
                    ]),
                    enableInteractiveSelection: true,
                    onChanged: (value) {
                      _formKey.currentState!.setState(() {});
                    },
                    textInputAction: TextInputAction.done,
                    onSaved: (newValue) {
                      _newProduct = Product(
                        id: _newProduct.id,
                        title: _newProduct.title,
                        description: _newProduct.description,
                        price: _newProduct.price,
                        imageUrl:
                            _formKey.currentState!.fields['urlImage']?.value,
                        isFavorite: _newProduct.isFavorite,
                      );
                    }),
                SizedBox(
                  height: 20,
                ),
                Container(
                  decoration: BoxDecoration(
                      border: Border.all(
                    color: Colors.black54,
                  )),
                  child: SizedBox(
                    height: 100,
                    width: 100,
                    child: (_formKey.currentState?.fields['urlImage']?.value ==
                            null)
                        ? Text('Proview Url image')
                        : Image.network(
                            _formKey.currentState?.fields['urlImage']!.value),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}`
where is the problem?

**Comment by Shahmirzali-Huseynov** [comment]
how solve the problem?
