### ISSUE TITLE
How can I handle the default selected item in FormBuilderDropdown?

### ISSUE THREAD

**Issue by SergeBerwert** [flutter-form-builder-ecosystem/flutter_form_builder#1113]
## Environment

"7.6.0"

## Describe your question
How can I handle the default selected item in FormBuilderDropdown? When the date contains a value that is not in the items list or the value is null is there a way to set a default value instead of getting an error?

**Comment by danvick** [comment]
That's how Flutter's DropdownField works.

Also, remember that the 'error' is a failed assertion and happens only in debug mode. In release mode, the default value becomes null if the value set is not in the list.
