### ISSUE TITLE
Is there a way to set textAlignVertical on fields like date picker or date range picker?

### ISSUE THREAD

**Issue by arguswaikhom** [flutter-form-builder-ecosystem/flutter_form_builder#1114]
## Environment

**Package version:**
7.6.0

## Describe your question

On fields like **FormBuilderTextField**, we have **textAlignVertical** to set the vertical alignment of the text but I'm unable to do it for the **FormBuilderDateTimePicker** field.

The way I do it now is by creating a fork and adding **textAlignVertical** in the **FormBuilderDateTimePicker**.  [Fork commit](https://github.com/arguswaikhom/flutter_form_builder/commit/6380d4bd06b5715e329cc3137cb4fe9eddd930c1
)

Is there an already existing way to receive this behaviour?

**Comment by deandreamatias** [comment]
Hi!
I think that this is the better and correct way. You can open a pull request with your changes

**Comment by arguswaikhom** [comment]
@deandreamatias - Added, please take a look.
