### ISSUE TITLE
Initial data to 

### ISSUE THREAD

**Issue by EricRootLee** [flutter-form-builder-ecosystem/flutter_form_builder#1115]
## Environment

**Package version:**

## Describe your question

How do I set initial data to the form builder just before it has been rendered or eve after, .

I have a map of data emulating the fields and keys that I want to populate in the form builder

**Comment by Shahmirzali-Huseynov** [comment]
how solve the problem ? @EricRootLee

**Comment by EricRootLee** [comment]
@Shahmirzali-Huseynov , i used the initial value attribute and a method to transform the json data to initial value.

```dart

 String? _populate({required String key}) {
    return json.data[key];
  }
 return FormBuilderDropdown<dynamic>(
                                  initialValue: _populate(
                                      key: data.data),
                                  name: data.name,
...


```
