### ISSUE TITLE
Create a nested Form

### ISSUE THREAD

**Issue by MatthiasM86** [flutter-form-builder-ecosystem/flutter_form_builder#1117]
Hi,
I tried to find an answer or example to my question, how can I build a nested Form? For example I have a contact form and want to add multiple phone numbers and addresses. I didn't found something like a FormArray where I can add multiple FormFields with the same names. Would be nice if you could give me a direction or an example.

BR Matthias

**Comment by deandreamatias** [comment]
I think that this issue is duplicated from this https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/239. I will close
