### ISSUE TITLE
Replacing duplicate Field

### ISSUE THREAD

**Issue by Shahmirzali-Huseynov** [flutter-form-builder-ecosystem/flutter_form_builder#1124]
## Environment

**Package version:**

```
   flutter_form_builder: ^7.6.0
  form_builder_extra_fields: ^8.3.0
  form_builder_validators: ^8.3.0
```

I'm using setState on my page, and when the page refreshes these warnings shown

```
flutter: Warning! Replacing duplicate Field for rank -- this is OK to ignore as long as the field was intentionally replaced
flutter: Warning! Ignoring Field unregistration for rank -- this is OK to ignore as long as the field was intentionally replaced
```

**Comment by deandreamatias** [comment]
Duplicated of #666

**Comment by Shahmirzali-Huseynov** [comment]
but there isn't a solution.

**Comment by Shahmirzali-Huseynov** [comment]
@deandreamatias I don't use   ` key: UniqueKey(),`

**Comment by awaisabbasaa11** [comment]
This issue is still occurring no matter if I use UniqueKey(), or Key(''), or no key at all can you please have a look, here is my code for this 
`Expanded(
            child: GetBuilder<MeetingController>(
              id: 'cms',
              builder: (c) {
                if (c.isError && c.errorMessage!.isNotEmpty) {
                  Utils.showSnack(c.errorMessage, isError: true);
                  c.errorMessage = '';
                }
                return Stack(
                  children: [
                    Padding(
                      padding: EdgeInsets.symmetric(horizontal: 3.w),
                      child: FormBuilder(
                        key: formKey,
                        child: SingleChildScrollView(
                          child: Column(
                            children: [
                              Space.y1,
                              ImagePickerWidget(
                                height: 20.h,
                                imageUrl: c.isEditMeetingEnabled
                                    ? c.meeting?.avatar
                                    : null,
                                lockAspectRatio: false,
                                borderWidth: 1.5,
                                initAndroidAspectRatioPreset:
                                    CropAspectRatioPreset.original,
                                backgroundColor: AppTheme.profileGreyBgColor,
                                customImageCallback: (file) {
                                  FocusManager.instance.primaryFocus!.unfocus();
                                  return c.selectedImage = file;
                                },
                                aspectRatio: const CropAspectRatio(
                                  ratioX: 16.0,
                                  ratioY: 9.0,
                                ),
                              ),
                              Space.y1,
                              Space.y0,
                              InputFormFieldV2(
                                name: 'title',
                                maxLines: 1,
                                maxLength: 255,
                                initialValue: c.isEditMeetingEnabled
                                    ? c.meeting!.title
                                    : '',
                                label: 'Title of the meeting'.tr,
                                validator: FormBuilderValidators.compose(
                                  [
                                    FormBuilderValidators.required(
                                      errorText: 'This field is required'.tr,
                                    ),
                                    FormBuilderValidators.minLength(
                                      6,
                                    ),
                                  ],
                                ),
                              ),
                              Space.y1,
                              Space.y0,
                              InputFormFieldV2(
                                key: Key(c.getDate()),
                                name: 'date',
                                maxLines: 1,
                                enabled: false,
                                label: 'Date'.tr,
                                initialValue: c.getDate(),
                                onTap: () {
                                  c.pickDate();
                                },
                              ),
                              Space.y1,
                              Space.y0,
                              Row(
                                crossAxisAlignment: CrossAxisAlignment.center,
                                mainAxisAlignment: MainAxisAlignment.center,
                                children: [
                                  Expanded(
                                    child: InputFormFieldV2(
                                      key: Key(c.fromTime.toString()),
                                      name: 'meetingFrom',
                                      maxLines: 1,
                                      enabled: false,
                                      label: 'Time'.tr,
                                      initialValue: c.fromTime.format(context),
                                      onTap: () async {
                                        FocusManager.instance.primaryFocus!
                                            .unfocus();
                                        final r = await showTimePicker(
                                          context: context,
                                          initialTime: c.fromTime,
                                          builder: (BuildContext context,
                                              Widget? child) {
                                            return child!;
                                          },
                                        );
                                        if (r != null) c.fromTime = r;
                                        c.updateListeners();
                                      },
                                    ),
                                  ),
                                  Space.x1,
                                  Container(
                                    height: AppDimensions.space(2.5) as double?,
                                    alignment: Alignment.bottomCenter,
                                    child: const Text('-'),
                                  ),
                                  Space.x1,
                                  Expanded(
                                    child: InputFormFieldV2(
                                      key: Key(c.toTime.toString()),
                                      name: 'meetingTo',
                                      maxLines: 1,
                                      enabled: false,
                                      label: '',
                                      initialValue: c.toTime.format(context),
                                      onTap: () async {
                                        FocusManager.instance.primaryFocus!
                                            .unfocus();
                                        final r = await showTimePicker(
                                          context: context,
                                          initialTime: c.toTime,
                                          builder: (
                                            BuildContext context,
                                            Widget? child,
                                          ) {
                                            return child!;
                                          },
                                        );
                                        if (r != null) c.toTime = r;
                                        c.updateListeners();
                                      },
                                    ),
                                  ),
                                ],
                              ),
                              Space.y1,
                              Space.y0,
                              InputFormFieldV2(
                                name: 'description',
                                maxLines: 6,
                                minLines: 4,
                                maxLength: 500,
                                initialValue: c.isEditMeetingEnabled
                                    ? c.meeting!.description
                                    : '',
                                label: 'Description'.tr,
                                alignLabelWithHint: true,
                                validator: FormBuilderValidators.compose(
                                  [
                                    FormBuilderValidators.required(
                                      errorText: 'This field is required'.tr,
                                    ),
                                    FormBuilderValidators.minLength(
                                      20,
                                    ),
                                  ],
                                ),
                              ),
                              Space.y1,
                              Space.y0,
                              InputFormFieldV2(
                                key: Key(c.address!),
                                name: 'address',
                                maxLines: 1,
                                initialValue: c.address,
                                label: 'Location'.tr,
                                maxLength: 400,
                                iconData: MaterialCommunityIcons.map_search,
                                onChange: (s) => c.address = s,
                                onIconTap: () => c.getCordsFromAddress(),
                                validator: FormBuilderValidators.compose(
                                  [
                                    FormBuilderValidators.required(
                                      errorText: 'This field is required'.tr,
                                    ),
                                    FormBuilderValidators.minLength(
                                      6,
                                    ),
                                  ],
                                ),
                              ),
                              Space.y1,
                              Space.y0,
                              ClipRRect(
                                borderRadius: CommonProps.cornerRadius,
                                child: SizedBox(
                                  height: 20.h,
                                  child: Container(
                                    color: AppTheme.meetingFieldBorderColor,
                                    padding: const EdgeInsets.all(2),
                                    child: Stack(
                                      children: [
                                        GoogleMap(
                                          myLocationEnabled: true,
                                          myLocationButtonEnabled: true,
                                          initialCameraPosition: CameraPosition(
                                            target: LatLng(
                                              c.lat!,
                                              c.lng!,
                                            ),
                                            zoom: 15,
                                          ),
                                          onMapCreated: (mc) =>
                                              c.mapController = mc,
                                          onCameraMove: (pos) =>
                                              c.mapLatLng = pos.target,
                                          onCameraIdle: () => c.getAddress(),
                                          onTap: (cord) {
                                            FocusManager.instance.primaryFocus!
                                                .unfocus();
                                            c.mapLatLng = cord;
                                            c.moveMapCamera(
                                              cord.latitude,
                                              cord.longitude,
                                            );
                                          },
                                          gestureRecognizers: {
                                            Factory<
                                                OneSequenceGestureRecognizer>(
                                              () {
                                                return EagerGestureRecognizer();
                                              },
                                            ),
                                          },
                                        ),
                                        Center(
                                          child: Icon(
                                            MaterialCommunityIcons.target,
                                            size: 8.w,
                                            color: AppTheme.primary,
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                              ),
                              Space.y1,
                              Space.y0,
                              AppButton(
                                onTap: () => c.createUpdateMeeting(formKey),
                                label: c.isEditMeetingEnabled
                                    ? 'Update'.tr
                                    : 'Submit'.tr,
                              ),
                              SizedBox(
                                height: 5.h,
                              ),
                            ],
                          ),
                        ),
                      ),
                    ),
                    Visibility(
                      visible: c.isLoading,
                      child: Positioned(
                        top: 0,
                        bottom: 0,
                        left: 0,
                        right: 0,
                        child: Container(
                          color: Colors.grey.withOpacity(0.01),
                          child: const Center(
                            child: CircularProgressIndicator.adaptive(),
                          ),
                        ),
                      ),
                    ),
                  ],
                );
              },
            ),
          ),`
