### ISSUE TITLE
Segmented Control

### ISSUE THREAD

**Issue by PRQAE** [flutter-form-builder-ecosystem/flutter_form_builder#1128]
Hi, I'm facing an issue with segmented control, it was ok but 2 months later it shows me this error after updating the package and flutter:

file:///C:/src/flutter/packages/flutter/lib/src/cupertino/segmented_control.dart:106:10
..\…\cupertino\segmented_control.dart:106
groupValue == null || children.keys.any((T child) => child == groupValue)
"The groupValue must be either null or one of the keys in the children map."
The relevant error-causing widget was:
  FormBuilderSegmentedControl<Object>

Flutter : 3.3.4 
Package: 7.7.0

**Comment by danvick** [comment]
@PRQAE Could you kindly include your code if possible?

From what I can deduce from the message, it seems like an assertion warning. It seems the value you've set as your initial value is not part of the list of items available for selection.
