### ISSUE TITLE
FormBuilderDropdown suffix icon is not aligned on value

### ISSUE THREAD

**Issue by globalwebforce** [flutter-form-builder-ecosystem/flutter_form_builder#1130]
![Capture](https://user-images.githubusercontent.com/100259991/198158173-851a772a-7432-4432-adec-bcff5e65e09e.PNG)

Package Version: 
flutter_form_builder: ^7.7.0

![image](https://user-images.githubusercontent.com/100259991/198159563-f730c4b2-e0d8-46a3-9533-91166efc3084.png)

**Comment by deandreamatias** [comment]
Hi!
I change the example code to test this and works fine with `suffixIcon`.

```
  FormBuilderDropdown<String>(
    name: 'gender',
    decoration: const InputDecoration(
      labelText: 'Gender',
      suffixIcon: Icon(Icons.close),
      hintText: 'Select Gender',
      border: OutlineInputBorder(),
    ),
    items: genderOptions
        .map((gender) => DropdownMenuItem(
              alignment: AlignmentDirectional.center,
              value: gender,
              child: Text(gender),
            ))
        .toList(),
  ),
```

![Screenshot 2022-10-29 19:09:42](https://user-images.githubusercontent.com/21011641/198844321-b84d7c1f-08d5-4e77-baa5-8584da7ed4a5.png)

If you use `suffix`, try align inside your widget

**Comment by vishalpatel1327** [comment]
Any updates on this ?
