### ISSUE TITLE
calling setState in the widget resets the form.

### ISSUE THREAD

**Issue by anovis** [flutter-form-builder-ecosystem/flutter_form_builder#1134]
I would like to toggle visibility of fields depending on the value of a checkbox (#316). 

I am trying to set the state of a seperate variable, but everytime I call setState the state of the form resets to its initial state. 

I defaulted a variable and toggle it via setState. everytime setState is called the form resets
```
Checkbox(
                      value: sameHours,
                      onChanged: (value) {
                        setState(() {
                          sameHours = value!;
                        })
                      },
                    ),
```
the following  attempt using `FormBuilderCheckbox` didn't reset the form, but never updates the checkbox state (ie setsate for the form is not called)
```
   FormBuilderCheckbox(
                      name: "same_hours",
                      title: YText("Same Every day?"),
                      onChanged: (value) {
                        setState(() {
                          sameHours = value!;
                        });
                      },
                    )
                    
 ```
                    
curious if I am doing something incorrect. or how i could toggle the visability of a field (external variable or internal) 
```
Visibility(
                        visible: samehour or _formKey.currentState?.value["same_hours"],
                        child: FormBuilderCupertinoDateTimePicker(
                            name: "same_open",
                            initialValue: DateTime(1, 1, 1, 9, 0).toUtc(),
                            inputType: CupertinoDateTimePickerInputType.time,
                            decoration: formInput("same_open", width: 120))),
                            
 ```
 
 using `_formKey.currentState?.value["same_hours"]` never updated the visibility

**Comment by deandreamatias** [comment]
Hi @anovis!
Try use  `_formKey.currentState?.instantValue["same_hours"]`
The difference between instantValue and value is that value is only update when save the form (`save()` method)

**Comment by anovis** [comment]
Ah!!! thats it. Appreciate the help.
