### ISSUE TITLE
Is it possible to have different formats for display and for editing?

### ISSUE THREAD

**Issue by myThorsten** [flutter-form-builder-ecosystem/flutter_form_builder#1138]
Hello :),
I have a question. I want to use a FormBuilderTextField to display a currency. Is it possible to display a formatted value to the user when the field is not being edited and only the number-value when it is edited? I believe that the group separators and currency symbol are helpful for the display, but they are in the way when editing.

I prepared some screenshots (I am from germany). While being edited:
![image](https://user-images.githubusercontent.com/9773490/199846060-4efdca5a-48bc-4fa9-8e13-506c1e5f3c87.png)

While not being edited:
![image](https://user-images.githubusercontent.com/9773490/199845883-3aec1541-0470-4fba-9775-a0247bda0691.png)

Thank you,
Thorsten Treffer

**Comment by deandreamatias** [comment]
Hi @myThorsten 
Maybe can set a currency inside text on left side of texfield by decoration property

**Comment by myThorsten** [comment]
So, here is how I did it:

![image](https://user-images.githubusercontent.com/9773490/200061081-ca331ae4-d4a4-41c6-957e-fe6823a83855.png)

1. the initial value has to be formatted because inputFormatters are only applied when the user inputs something.
2. valueTransformer has to remove added symbols by the inputFormatter
3. inputFormatter adds group-symbols and suffixes
4. for validators to still work the added symbols by the inputFormatter has to be removed

Not perfect, because the symbols are still displayed when the user inputs values, but sufficient.

**Comment by RodolfoSilva** [comment]
Another alternative:

```dart
import 'package:currency_text_input_formatter/currency_text_input_formatter.dart';
import 'package:flutter/material.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';

class FormBuilderCurrencyField extends StatelessWidget {
  const FormBuilderCurrencyField({
    super.key,
    required this.name,
    this.symbol = r'R$',
    this.locale = 'pt_BR',
    this.decimalDigits = 2,
    this.decoration,
    this.validator,
  });

  final String symbol;
  final String locale;
  final String name;
  final int decimalDigits;
  final String? Function(double?)? validator;
  final InputDecoration? decoration;

  @override
  Widget build(BuildContext context) {
    return FormBuilderField<double>(
      name: name,
      validator: validator,
      builder: (field) {
        final formatter = CurrencyTextInputFormatter(
          symbol: symbol,
          locale: locale,
          decimalDigits: decimalDigits,
        );

        return TextFormField(
          initialValue: field.value != null
              ? formatter.format(field.value!.toStringAsFixed(2))
              : null,
          decoration: (decoration ?? const InputDecoration()).copyWith(
            errorText: decoration?.errorText ?? field.errorText,
            hintText: decoration?.hintText ?? formatter.format("0.00"),
          ),
          onChanged: (price) =>
              field.didChange(formatter.getUnformattedValue() * 1.0),
          inputFormatters: [formatter],
        );
      },
    );
  }
}

```
