### ISSUE TITLE
Change FormBuilderTextField decoration programmatically

### ISSUE THREAD

**Issue by mohammedX6** [flutter-form-builder-ecosystem/flutter_form_builder#1149]
## Ios and android

** 7.7.0:**

I want  to change FormBuilderTextField decoration field programmatically from another field

**Comment by deandreamatias** [comment]
Hi!
One solution that I think is create a InputDecoration var and update with app state, like setState or other state management.
With FlutterFormBuilder you can access to decoration (get) but can't update this value directly
