### ISSUE TITLE
FormBuilderSwitchCupertino exist?

### ISSUE THREAD

**Issue by waperp** [flutter-form-builder-ecosystem/flutter_form_builder#1150]
I would like to know if there is any way to Switch for IOS available

**Comment by deandreamatias** [comment]
Hi!
Sadly, this package don't support most of Cupertino widgets. Take a look on this issue for more context https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/718
Sorry for that

**Comment by danvick** [comment]
To be a bit more precise, [the package supports *any input widget*](https://medium.com/@danvickmiller/building-a-custom-flutter-form-builder-field-c67e2b2a27f4) by using the `FormBuilderField` class.

You can easily create a FormBuilder field with a `CupertinoSwitch` by wrapping it inside a `FormBuilderField` widget like so:

```Dart
FormBuilderField<bool>(
    name: 'name',
    onChanged: (val) => debugPrint(val.toString()),
    builder: (FormFieldState field) {
        return CupertinoFormRow(
            prefix: const Text('Switch: '),
            error: field.errorText != null ? Text(field.errorText!) : null,
            child: CupertinoSwitch(
                value: field.value ?? false,
                onChanged: (value) => field.didChange(value),
            ),
        );
    },
),
```

We'll consider adding common Cupertino fields in the next major version of the package.

**Comment by deandreamatias** [comment]
I created a [new package](https://pub.dev/packages/form_builder_cupertino_fields) for only Cupertino fields
