### ISSUE TITLE
Is it possible to put label in front of FormField

### ISSUE THREAD

**Issue by MarcVanDaele90** [flutter-form-builder-ecosystem/flutter_form_builder#1151]
## Environment

**Package version:**

## Describe your question
Our designer made something like this, where the labelText is in front of the inputfield
![image](https://user-images.githubusercontent.com/90178346/203548519-1f96d008-5f70-4600-a76b-a722e8cca5ee.png)

Is this currently supported? 
If not, I can wrap every FormField in a Row with a Text() widget in front of it 
but this would result in quite some boilerplate code so I wonder whether there are more elegant approaches?

**Comment by deandreamatias** [comment]
Hi @MarcVanDaele90!
Try use prefix property inside decoration property, like this [example](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder#implement-reset-clear-or-other-button-into-formbuilderfield)

**Comment by MarcVanDaele90** [comment]
@deandreamatias Thanks!  That should work indeed!
