### ISSUE TITLE
Search method for a long list

### ISSUE THREAD

**Issue by jmpavan** [flutter-form-builder-ecosystem/flutter_form_builder#1153]
## Environment

 7.7.0 

## Description
Have a search method for a long list. 
For example a text box where to write some of the letters of the searched item.

**Comment by jmpavan** [comment]
Obviously I mean about a FormBuilderDropdown,

**Comment by deandreamatias** [comment]
Hi!
Maybe [this](https://github.com/flutter-form-builder-ecosystem/form_builder_extra_fields/blob/main/lib/src/fields/form_builder_searchable_dropdown.dart)?
Try [this package](https://pub.dev/packages/form_builder_extra_fields)

**Comment by jmpavan** [comment]
Thank you, I will try it.

Jorge Mario Paván
+54 9 11 5327 9247
***@***.***

[pavan.jpg]

Sobre 23/11/2022 18:30:53, Matias de Andrea ***@***.***> escribió:
Hi!
Maybe this [https://github.com/flutter-form-builder-ecosystem/form_builder_extra_fields/blob/main/lib/src/fields/form_builder_searchable_dropdown.dart]?
Try this package [https://pub.dev/packages/form_builder_extra_fields]
