### ISSUE TITLE
FormBuilderDateTimePicker locale bugs

### ISSUE THREAD

**Issue by yichaosun** [flutter-form-builder-ecosystem/flutter_form_builder#1158]
hi bro,
when I use FormBuilderDateTimePicker and config locale(here zh_CN),
```dart
                    FormBuilderDateTimePicker(
                      name: 'taskTime',
                      decoration: InputDecoration(labelText: logic.taskTime),
                      locale: Get.deviceLocale,
                    ),
```

the date pick ui is correct with Chinese,
<img width="306" alt="image" src="https://user-images.githubusercontent.com/7195037/205079461-95dc01a9-0d19-46ae-92e0-93ad7ad5a055.png">

but next, the time pic ui still show in English
<img width="281" alt="image" src="https://user-images.githubusercontent.com/7195037/205079509-d114faf7-0228-453a-92b9-ced39bdfbccf.png">

**Comment by yichaosun** [comment]
when I add this , the second ui ,time picker show  correctly!

```dart
      supportedLocales: [
        const Locale('en', 'US'), 
        const Locale('zh', 'CN'), 
      ],
```

but the first ui datep icker don't required this

**Comment by AlBlanc** [comment]
Unfortunately, it seems  flutter [`TimePickerDialog`](https://api.flutter.dev/flutter/material/TimePickerDialog-class.html) does not provide a `locale` parameter.

After reading `DatePickerDialog` source code, i am going to give a try to `Localizations.override`.

Be right back ;)
