### ISSUE TITLE
How to implement IOS 15 scan text feature in Flutter TextField

### ISSUE THREAD

**Issue by felix0324324** [flutter-form-builder-ecosystem/flutter_form_builder#1159]
I want to add ios 15's new scan text feature in my flutter textfield. I have set my target deployment as 15.2 for both project and podfile and yet the option is not coming like in the featured image. If anyone out there know how can it be done, it will be a great help.

![EHA78](https://user-images.githubusercontent.com/16462532/205451165-7697fc48-0920-4c20-808b-6175b01744d3.png)

**Comment by deandreamatias** [comment]
Hi @felix0324324 
You can do it this with _native_ TextField of Flutter?

**Comment by felix0324324** [comment]
> Hi @felix0324324 You can do it this with _native_ TextField of Flutter?

So....I cannot use "flutter_form_builder" functions?

**Comment by deandreamatias** [comment]
I made a question because if dont work with native form field, cant be work with this package

**Comment by felix0324324** [comment]
> I made this question because if don't work with native form field, also cant be work with this package

I have to click twice to focus the "Native TextField". 
The first time click on "Native TextField" seems nothing happens.

**Comment by AlBlanc** [comment]
After investigation, flutter does not provide a way to use the "scan text" ios feature natively. As it does not use native `UITextField` from iOS we can't provide a quick and easy way to implement it.

The best approach would be to create another widget using [flutter native text input package](https://pub.dev/packages/flutter_native_text_input) (in a separate flutter package)
