### ISSUE TITLE
[QUESTION] Is there a way to convert JSON to Flutter Form Builder

### ISSUE THREAD

**Issue by isAlmogK** [flutter-form-builder-ecosystem/flutter_form_builder#1160]
## Environment
Lastest Flutter

**Package version:**
Latest 

## Describe your question
I wanted to know if there is a way to use JSON to build Flutter Form Builder with the different input options

**Comment by deandreamatias** [comment]
Directly no. You can convert json to some model and create a logic to generate form builder inputs
