### ISSUE TITLE
content padding is just for textfield, not error text, how to achieve it?

### ISSUE THREAD

**Issue by stoneLee81** [flutter-form-builder-ecosystem/flutter_form_builder#1161]
The textfield does not seem to have the effect in the picture now?

![image](https://user-images.githubusercontent.com/18001708/205564132-67a777a2-0bea-4cbe-b987-768fe3ba1b5f.png)

**Comment by deandreamatias** [comment]
Hi @stoneLee81,
Can provide a minimal example code?
We use InputDecoration to implement this. Is the same way that _native_ TextField from Flutter. If you can do it with TextField, you will can do with FormBuilderTextField

**Comment by stoneLee81** [comment]
The display effect of textfield is the figure one, Figure 2 is the effect I expected。flutter textfield widget, content padding changed, the error text padding is also changed.

**Comment by stoneLee81** [comment]
for instance, the sample code here, when I used conentPadding to adjust textfield display, label& error text padding is also changed. It's textfield widget attributes.
`FormBuilderTextField(
                      name: 'age',
                      decoration: InputDecoration(
                        contentPadding: const EdgeInsets.all(10), 
                        labelText: 'Age',
                        errorText: 'hello',
                        ) `

**Comment by stoneLee81** [comment]
@deandreamatias
