### ISSUE TITLE
How do i handle a dynamic list of items?

### ISSUE THREAD

**Issue by shannon-rodricks** [flutter-form-builder-ecosystem/flutter_form_builder#1164]
**7.7.0**

I have a usecase where the user can create a list of pricing options for an item.
Each of these items contains:
Type - A user created name for the pricing type (String)
Cost - The actual value (String -> double) 

This list could vary from 0 to a hypothetical maximum of 10.
This is all contained within a single field "pricing"
An example result:
```
[
	{
		"type": "General"
		"cost": 400,
	},
	{
		"type": "Early bird",
		"cost": 200,
	}
]
```
A similar json can also be provided to it via the initial value, in the case where an existing pricing structure is being edited.

How do I implement this optimally?

I've attempted to create a FormBuilderField with a nested form (and a listview within it), but interactions cause it to bug out.
Ive read a response about dynamic fields and using register but Im not sure how to use it in this context.
Any help would be appreciated!

**Comment by shannon-rodricks** [comment]
Additional information.
This field is within a nested form ("requirements") within the main form.

**Comment by deandreamatias** [comment]
This is a question relative to your code work, I can't help too much
