### ISSUE TITLE
Crop form_builder_image_picker

### ISSUE THREAD

**Issue by mstfkhazaal** [flutter-form-builder-ecosystem/flutter_form_builder#1166]
How can crop image with form_builder_image_picker??

**Comment by deandreamatias** [comment]
Nop

**Comment by mstfkhazaal** [comment]
> Nop

There is no way?😥

**Comment by mstfkhazaal** [comment]
Is there a method before save image?
Like beforeChange()

**Comment by deandreamatias** [comment]
You can read the form field value, load the image value and load to some widget to crop
