### ISSUE TITLE
Multi column form

### ISSUE THREAD

**Issue by punitganshani** [flutter-form-builder-ecosystem/flutter_form_builder#1174]
I am trying to build a multi-column form and not able to figure how to build a matrix based form. Most of the examples are single column (or single child) with each question stacked to previous one.

Example. A table with 3 rows

<img width="942" alt="image" src="https://user-images.githubusercontent.com/1032553/211561317-96ba2964-920d-4196-8a68-959a56699267.png">

Do you have any sample that produces a working form with this layout?

**Comment by deandreamatias** [comment]
Hi @punitganshani 
Your question is related to a design or a form functionality?

**Comment by punitganshani** [comment]
I'm looking for a sample that has multi row, multi-column layout

**Comment by deandreamatias** [comment]
The issues is only for questions related with flutter form builder. A multi column layout is out of scope.

In other hand, maybe [Table](https://api.flutter.dev/flutter/widgets/Table-class.html) can help you
