### ISSUE TITLE
How can I do a FormBuilderField that returns a Map<String,dynamic>? 

### ISSUE THREAD

**Issue by lucianokapluk** [flutter-form-builder-ecosystem/flutter_form_builder#1175]
## Hi, I need to do something like this, where _formkey has a metadata which is Map<String,dynamic>, any idea how can i do it?

{  
  "id": 0,
  "description": "string",
  "logo": "string",
  "name": "string",
  "company_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "subscription_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  "metadata": {"option1": "", "option2": ""}
}

**Comment by deandreamatias** [comment]
_formKey.currentState.values or something like this don't help you?
Take a look on all formKey properties

**Comment by lucianokapluk** [comment]
Yes i know @deandreamatias ,but my question is how do I make "metadata" of type Map<String,dynamic>, inside the formKey.currentState.values?
