### ISSUE TITLE
Issue with rebuilding form children with different keys.

### ISSUE THREAD

**Issue by EhabSalah** [flutter-form-builder-ecosystem/flutter_form_builder#1181]
## Environment

**Package version:^6.1.0+1**

## Describe your question
Rebuild the form children with new ones but only with different keys, not updating the `_fields` list children keys! as it keep exists in the form state with the old fields key names

![image](https://user-images.githubusercontent.com/24505720/215331524-2f30cc7f-857d-48ae-8a3e-5ce032da4916.png)

**Comment by deandreamatias** [comment]
Hi
If this is a issue, please use a bug template to report it
Thanks
