### ISSUE TITLE
Material 3 chip default colors looks pretty strange    

### ISSUE THREAD

**Issue by bbence84** [flutter-form-builder-ecosystem/flutter_form_builder#1182]
When using the useMaterial3: true for the MaterialApp, the colors in dark mode at least look quite strange. I am not overriding any colors, yet this is what I get:

![Rendering issue](https://i.imgur.com/ymcQEvc.png)

The other controls look more or less OK, but I am not sure if there has been extensive testing on Material 3 for flutter_form_builder. Otherwise, I am really happy with this package. :) 

Thanks!

**Comment by deandreamatias** [comment]
This is related to theme configuration. You can configure on your global theme or on Form Field properties, like `decoration`
