### ISSUE TITLE
Example code at pub.dev doesn't compile

### ISSUE THREAD

**Issue by lukehutch** [flutter-form-builder-ecosystem/flutter_form_builder#1187]
In the example code at pub.dev, the following line does not compile:

```dart
supportedLocales: FormBuilderLocalizations.delegate.supportedLocales,
```

I get `The getter 'supportedLocales' isn't defined for the type 'LocalizationsDelegate<FormBuilderLocalizationsImpl>'.`

**Comment by deandreamatias** [comment]
Solved in 7.8.0
