### ISSUE TITLE
solving dependencies... (3.2s) Because every version of form_builder_validators depends on flutter_localizations from sdk which depends on intl 0.18.0, every version of form_builder_validators requires intl 0.18.0.

### ISSUE THREAD

**Issue by OmerAYDINOGLU** [flutter-form-builder-ecosystem/flutter_form_builder#1191]
Resolving dependencies... (3.2s)
Because every version of form_builder_validators depends on flutter_localizations from sdk which depends on intl 0.18.0, every version of form_builder_validators requires intl 0.18.0.
And because flutter_form_builder >=7.0.0-beta.0 depends on intl ^0.17.0, flutter_form_builder >=7.0.0-beta.0 is incompatible with form_builder_validators.
So, because pixr depends on both flutter_form_builder ^7.7.0 and form_builder_validators ^8.4.0, version solving failed.

**Comment by deandreamatias** [comment]
Take a look on [this issue](https://github.com/flutter-form-builder-ecosystem/form_builder_validators/issues/35)
