### ISSUE TITLE
Because flutter_form_builder 7.8.0 depends on intl ^0.17.0 but intl ^0.18.0 is required by many packages

### ISSUE THREAD

**Issue by aintend-com** [flutter-form-builder-ecosystem/flutter_form_builder#1196]
## Environment

**Package version:**

<details>
  <summary>Flutter doctor</summary>
Because flutter_form_builder 7.8.0 depends on intl ^0.17.0 and no versions of flutter_form_builder match >7.8.0 <8.0.0, flutter_form_builder ^7.8.0 requires intl ^0.17.0.
So, because fitorm depends on both intl ^0.18.0 and flutter_form_builder ^7.8.0, version solving failed.
pub get failed
command: "C:\src\flutter\bin\cache\dart-sdk\bin\dart __deprecated_pub --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "C:\src\flutter",
  "PUB_ENVIRONMENT": "flutter_cli:get",
  "PUB_CACHE": "C:\Users\admin\AppData\Local\Pub\Cache",
}
exit code: 1

</details>

<details>
  <summary>Code sample</summary>

```dart
```

</details>

## Description

**Expected behavior:**

**Current behavior:**

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by deandreamatias** [comment]
#1911 duplicated
