### ISSUE TITLE
Assertion in unregisterField() should not fire if already unregistered

### ISSUE THREAD

**Issue by tmpfs** [flutter-form-builder-ecosystem/flutter_form_builder#1203]
Thanks for the library, it is really useful.

I am working with a lot of dynamic form fields that need to be added and removed (think lists) and I sometimes see this error:

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown while finalizing the widget tree:
flutter: 'package:flutter_form_builder/src/form_builder.dart': Failed assertion: line 198 pos 12:
flutter: '_fields.containsKey(name)': is not true.
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      FormBuilderState.unregisterField (package:flutter_form_builder/src/form_builder.dart:198:12)
flutter: #3      FormBuilderFieldState.dispose (package:flutter_form_builder/src/form_builder_field.dart:156:24)
```

Because my form fields are dynamic I am manually unregistering as I remove them, I have tried `clearValueOnUnregister` but that doesn't always seem to clear the state and removing then adding entries to a list can see previous values.

The ergonomics for working with dynamic form fields could really use some attention IMO but in the meantime could we please just remove this assertion.

If the field does not exist (has already been unregistered) then the code can just ignore it - right?

**Comment by deandreamatias** [comment]
@tmpfs If you can add some minimal example code, I really appreciate

**Comment by francescreig** [comment]
Hello! I am also interested on this topic, since it happens me the same. When I have a dynamic form (for exemple a list) where you could add or remove items, specially **remove**, it shows this assertion and the form fields seems that they are not updated (only when there's a new trigger on an existing field, (like typing on another form text field).
What it would be the best approach to delete an item from  a form that is mainly a growable list of, for instance, FormBuilderTextFields?

**Comment by zaid2kaz** [comment]
> Hello @deandreamatias! I am also interested on this topic, since it happens me the same. When I have a dynamic form (for exemple a list) where you could add or remove items, specially **remove**, it shows this assertion and the form fields seems that they are not updated, only when there's a new trigger on an existing field, (like typing on another form text field). What it would be the best approach to delete an item from a form that is mainly a growable list of, for instance, FormBuilderTextFields?

same issue here
