### ISSUE TITLE
How do you format a formslider to have accompanying text?

### ISSUE THREAD

**Issue by mfizz1** [flutter-form-builder-ecosystem/flutter_form_builder#1207]
As the title states I have a formslider which which can select values from 1-60 in divisions of 10. 

These are minutes, how can I show "10 mins" as the text at the bottom instead of just "10"?

**Comment by deandreamatias** [comment]
With `formslider` is `FormBuilderSlider` field?
I think that need implement this feature, [like on FormBuilderRangeSlider](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/blob/4e00812568bbba655a174811895c071f29ed7afa/lib/src/fields/form_builder_slider.dart#L10).
If you can, please create a pull request with this changes, I will really appreciate. Thanks
