### ISSUE TITLE
Flutter : copy/paste text field menu display issue

### ISSUE THREAD

**Issue by fakhry-alnaffar** [flutter-form-builder-ecosystem/flutter_form_builder#1216]
I'm working on a login form, I'm using the library [flutter_form_builder](https://pub.dev/packages/flutter_form_builder): [^7.8.0](https://pub.dev/packages/flutter_form_builder/versions/7.8.0). Unfortunately, for some time I have been facing this problem: The copy/paste menu does not appear, but seems to offer a "Zoom".

**Comment by kvbogdanov** [comment]
same problem

**Comment by deandreamatias** [comment]
Duplicated https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/1202
