### ISSUE TITLE
Cascading or dependent fields

### ISSUE THREAD

**Issue by abdallah-odeh** [flutter-form-builder-ecosystem/flutter_form_builder#1218]
## Environment

**Package version:** ^7.8.0

## Describe your question
Is there a way to hide/show a field according to other field's value?
let's say I have a json that contains two fields, dropdown and a textfield, I want to display the textfield only if the selected value of the dropdown is a specific value
for example, 
I have **country** dropdown & **citizens count** textfield, I want to show the **citizens count** textfield only if the value of country is "Palestine" for example

**Comment by deandreamatias** [comment]
Maybe [this](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/920#issuecomment-1048929319) and [this](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/630) issue can help you

**Comment by deandreamatias** [comment]
Added conditional use case to examples
https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/pull/1237
