### ISSUE TITLE
Change field attributes at run time

### ISSUE THREAD

**Issue by abdallah-odeh** [flutter-form-builder-ecosystem/flutter_form_builder#1221]
## Environment

**Package version:** ^7.8.0

## Describe your question
I am trying to build a dynamic form (from json to Flutter fields) using your very helpful package
but I facing some issues,

1.  Change **readOnly** or **disabled** attribute of a textfield depending on a dropdown selection;
     Let's say I have a dropdown contains two options, **enable & disable**, and there is a textfield below it, I want to change the fields **readOnly** or **disabled** property according to what the user selects from the dropdown menu

2. I have two date pickers, **start date** & **end date**, when the user change the start date I want to limit the the end date's range to prevent the user from selecting an older date,
   same for the start date, when the user change the end date, I want to disable all dates after the selected end date
  
how can we achieve that without re-parse the json data to form and fill it up with the previously selected data?

**Comment by deandreamatias** [comment]
1. I think that here, your `Form` always will be `enable: false` and on each FormField (ex: FormBuilderTextField) you will be switch the parameter `readOnly` with some state management
2. This can solve with validators and state management. When set your **start date**, on onChange set the value to use on validator and the property `initialDate` on Datepicker

On next time, I suggest that you open two separated questions. Thanks

**Comment by abdallah-odeh** [comment]
@ambr89 
I found a dummy workaround that works but I don't like the solution,
if I wanted to change any field's attribute I will inject the new attribute in it's json, decode it again and then replace it in the same index
this means that the old widget get's disposed a new widget is built and added to the screen

**Comment by abdallah-odeh** [comment]
@deandreamatias 
No, the form won't be `enable: false`, 
a sample of what happens in my case, 
I have a dropdown & a textField, 
the dropdown contains two options, `Enable & Disable`
if the user chose `Enable` then the textfield will be enabled and the user can type whatever he wants in it
if the user chose `Disable` then the textfield will be disabled and the user can't type anything in it
