### ISSUE TITLE
focusOnInvalid - Validate on invalid bug

### ISSUE THREAD

**Issue by DaBaser123** [flutter-form-builder-ecosystem/flutter_form_builder#1230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

8.0.0

### Flutter doctor

<details>
  <summary>Flutter doctor</summary>

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.1 22C65 darwin-arm64, locale sv-SE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.77.3)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

### Minimal code example

<details>
  <summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';
import 'package:form_builder_validators/form_builder_validators.dart';

main() {
  runApp(const MaterialApp(home: LoginView(),),);
}

class LoginView extends StatefulWidget {
  const LoginView({Key? key}) : super(key: key);

  @override
  State<LoginView> createState() => _LoginViewState();
}

class _LoginViewState extends State<LoginView> {
  final _formKey = GlobalKey<FormBuilderState>();
  bool validateOnInteraction = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ConstrainedBox(
          constraints: const BoxConstraints(maxWidth: 400),
          child: FormBuilder(
            // This will trigger validation with focusOnInvalid set to true with no way of turning it off
            // When two fields "A" and "B" are invalid at the same time, the focus might always be requested on "A"
            // This makes it impossible to write anything on the "B" field
            autovalidateMode: validateOnInteraction ? AutovalidateMode.onUserInteraction : AutovalidateMode.disabled,
            key: _formKey,
              child: Column(
                mainAxisSize: MainAxisSize.min,
            children: [
              FormBuilderTextField(
                name: "email",
                keyboardType: TextInputType.emailAddress,
                decoration: const InputDecoration(
                  labelText: "Email",
                ),
                validator: FormBuilderValidators.compose([
                  FormBuilderValidators.required(errorText: "Email is required"),
                  FormBuilderValidators.email(errorText: "Invalid email address"),
                ]),
              ),
              SizedBox(height: 20),
              FormBuilderTextField(
                name: "password",
                obscureText: true,
                decoration: const InputDecoration(
                  labelText: "Password",
                ),
                validator: FormBuilderValidators.compose([
                  FormBuilderValidators.required(
                      errorText: "Password is required"),
                  FormBuilderValidators.minLength(8,
                      errorText: "Password must be at least 8 characters long"),
                ]),
              ),
              SizedBox(height: 20),
              ElevatedButton(onPressed: () {
                _formKey.currentState?.saveAndValidate(focusOnInvalid: false);
              }, child: Text("Save and validate, focusOnInvalid: false")),
              SizedBox(height: 20),
              ElevatedButton(onPressed: () {
                setState(() {
                  validateOnInteraction = !validateOnInteraction;
                });
              }, child: Text("AutovalidateMode: ${validateOnInteraction ? 'onUserInteraction' : 'disabled'}")),
            ],
          )),
        ),
      ),
    );
  }
}
```

</details>

### Current Behavior

No way to disable focusOnInvalid option on autovalidateMode and saveAndValidate seem to still request focus to invalid fields even when focusOnInvalid is set to false. Currently autovalidate is unusable if you have two invalid fields and field "A" is requesting focus on each input making it impossible to fill out field "B" while field "A" is invalid.

### Expected Behavior

For saveAndValidate to not request focus on invalid fields when it's set to false. For autoValidate i think the expected behavior would be for it to never request focus since the field taking focus might be different from the one being filled in.

### Steps To Reproduce

1. Run the code on Chrome.

### Aditional information

https://user-images.githubusercontent.com/31376097/234837755-7d2e9b1e-e137-45f7-af9c-c5b0463f3470.mov

**Comment by Baghdady92** [comment]
i have same issue 
i downgrade to version flutter_form_builder ^7.8.0
this version work fine for me

**Comment by angwandi** [comment]
even version 9.0.0 still has the issue. Any workaround? I really would not like to downgrade.

**Comment by deandreamatias** [comment]
I'm working on update all packages to Flutter 3.10 and Dart 3. When I finish, this will be my next issue to work

**Comment by sgruhier** [comment]
I hope you'll be able to fix that quickly because now it's unusable on flutter 3.10/dart 3. And it's not possible to use previous version on flutter 3.10/dart 3 because of `intl` dependency :(

**Comment by sgruhier** [comment]
thanks

**Comment by deandreamatias** [comment]
This is related to this note?

> If a invalid field is from type TextField and will focused, the form will auto scroll to show this invalid field. In this case, the automatic scroll happens because is a behavior inside the framework, not because [autoScrollWhenFocusOnInvalid] is true.

**Comment by deandreamatias** [comment]
This bug can split in two parts.
1. In first way, the `validate` method should not focus any invalid field when `focusOnInvalid` is false
2. In second way, the autovalidate should not change focus to another field when a field already has focus

**Comment by deandreamatias** [comment]
Please @sgruhier @angwandi @Baghdady92 and @DaBaser123 take a look on open PR and if this solutions is correct

**Comment by sgruhier** [comment]
I still have that issue, I'm gonna share a quick video

**Comment by sgruhier** [comment]
As you can see as soon as I type something in first field, it focuses the other one. 
https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/assets/3385/211ec359-9dea-463c-9e9f-7255cadf4003

I used 
``` 
  flutter_form_builder:
    git:
      url: https://github.com/flutter-form-builder-ecosystem/flutter_form_builder.git
      branch: fix-1230-improve-focus-validation
```

**Comment by deandreamatias** [comment]
Ok @sgruhier 
I need a minimal example code to test this with new changes

**Comment by Baghdady92** [comment]
> git:
>       url: https://github.com/flutter-form-builder-ecosystem/flutter_form_builder.git
>       branch: fix-1230-improve-focus-validation

i tried your work still not working if you need example this is mine 
put this list in Column and test it 

[ FormBuilderTextField(
                    name: 'customername',
                    textAlign: TextAlign.center,
                    validator: FormBuilderValidators.minLength(15,
                        errorText: 'required')),
                SizedBox(height: 20),
                FormBuilderDropdown(
                  name: 'gender',
                  validator: FormBuilderValidators.compose([
                    FormBuilderValidators.required(
                        errorText: 'Gender is requird')
                  ]),
                  items: ['Male', 'Female']
                      .map((gender) => DropdownMenuItem(
                            value: gender,
                            child: Text(gender),
                          ))
                      .toList(),
                ),

                SizedBox(height: 20),
                //birthday
                FormBuilderDateTimePicker(
                  name: 'birthday',
                  inputType: InputType.date,
                  format: DateFormat('y-M-d'),
                  textAlign: TextAlign.center,
                  validator: FormBuilderValidators.required(
                      errorText: 'Birthday is required'),
                ),
                SizedBox(height: 20),
                //
                FormBuilderTextField(
                  name: 'phone2',
                  initialValue: e.phone2,
                  style: formTextStyle,
                  decoration: formTextDecoration('Phone2'),
                  textAlign: TextAlign.center,
                  validator: FormBuilderValidators.integer(
                      errorText: 'Phone2 is required'),
                ),

                SizedBox(height: 20),
                //job
                FormBuilderTextField(
                  name: 'job',
                validator: FormBuilderValidators.required(
                      errorText: 'job is required'),
                ),

                SizedBox(height: 20),

                FormBuilderTextField(
                  name: 'address',                
                  validator: FormBuilderValidators.required(
                      errorText: 'Address is required'),
                ),]

**Comment by deandreamatias** [comment]
@Baghdady92 I try to reproduce the error with your code and the [PR branch](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/pull/1254), but I can't.
Like I said [here](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/1230#issuecomment-1552685796), has two problems. Which still happens?

You can see in this video the code that this error no happens

[Screencast from 27-05-23 11:39:58.webm](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/assets/21011641/bef32605-5cb9-4d04-afb5-5edd7c725994)

**Comment by deandreamatias** [comment]
Thanks for testing @jdar 
I will waiting. If no one can share a reproducible minimal code and video with the error, I will merge de PR

**Comment by phuchuynhStrong** [comment]
@deandreamatias I confirm that the PR branch fixed the problem 1 & 2. 
```
import 'package:flutter/material.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';
import 'package:form_builder_validators/form_builder_validators.dart';

class ValidateForm extends StatefulWidget {
  const ValidateForm({super.key});

  @override
  State<ValidateForm> createState() => _ValidateFormState();
}

class _ValidateFormState extends State<ValidateForm> {
  final _formKey = GlobalKey<FormBuilderState>();
  bool isValid = false;
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        FormBuilder(
          autovalidateMode: AutovalidateMode.always,
          // onChanged: () {
          //   setState(() {
          //     isValid = _formKey.currentState?.saveAndValidate(
          //           focusOnInvalid: false,
          //         ) ==
          //         true;
          //   });
          // },
          key: _formKey,
          child: Column(
            children: [
              FormBuilderTextField(
                name: 'street',
                validator: FormBuilderValidators.compose([
                  FormBuilderValidators.required(),
                ]),
                keyboardType: TextInputType.text,
              ),
              FormBuilderTextField(
                name: 'name',
              ),
              IconButton(
                onPressed: isValid ? () {} : null,
                icon: Icon(Icons.abc),
              ),
            ],
          ),
        ),
      ],
    );
  }
}

```
Here is video using this code with PR branch [https://jmp.sh/VOV6mbea](url). And a video show the problem 2 with main version (9.0.0) [https://jmp.sh/VOV6mbea](url). Both using above code.

**Comment by deandreamatias** [comment]
@phuchuynhStrong Thanks for feedback. I will merge the PR
