### ISSUE TITLE
[FormBuilderDropdown]: use DropdownButtonFormField

### ISSUE THREAD

**Issue by listepo** [flutter-form-builder-ecosystem/flutter_form_builder#1231]
It would be nice to use [DropdownButtonFormField](https://api.flutter.dev/flutter/material/DropdownButtonFormField-class.html) for FormBuilderDropdown

**Comment by deandreamatias** [comment]
Can test this on [pre-release 9.0.0-dev.1](https://pub.dev/packages/flutter_form_builder/versions/9.0.0-dev.1)

**Comment by listepo** [comment]
Nice, thanks
