### ISSUE TITLE
Bug when flutter pub get 

### ISSUE THREAD

**Issue by fakhry-alnaffar** [flutter-form-builder-ecosystem/flutter_form_builder#1244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

last version

### Flutter doctor

Because eureeca depends on flutter_form_builder from git which depends on intl ^0.17.0, intl ^0.17.0 is required.
So, because eureeca depends on intl ^0.18.1, version solving failed.

### Minimal code example

Because eureeca depends on flutter_form_builder from git which depends on intl ^0.17.0, intl ^0.17.0 is required.
So, because eureeca depends on intl ^0.18.1, version solving failed.

### Current Behavior

Because eureeca depends on flutter_form_builder from git which depends on intl ^0.17.0, intl ^0.17.0 is required.
So, because eureeca depends on intl ^0.18.1, version solving failed.

### Expected Behavior

Because eureeca depends on flutter_form_builder from git which depends on intl ^0.17.0, intl ^0.17.0 is required.
So, because eureeca depends on intl ^0.18.1, version solving failed.

### Steps To Reproduce

Because eureeca depends on flutter_form_builder from git which depends on intl ^0.17.0, intl ^0.17.0 is required.
So, because eureeca depends on intl ^0.18.1, version solving failed.

### Aditional information

Because eureeca depends on flutter_form_builder from git which depends on intl ^0.17.0, intl ^0.17.0 is required.
So, because eureeca depends on intl ^0.18.1, version solving failed.

**Comment by deandreamatias** [comment]
Duplicated
