### ISSUE TITLE
general: update dependency of `intl` to `any` after upgrading to latest Flutter version

### ISSUE THREAD

**Issue by bastibense** [flutter-form-builder-ecosystem/flutter_form_builder#1246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

9.0.0-dev.1

### Flutter doctor

<details>
  <summary>Flutter doctor</summary>

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E261 darwin-x64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.78.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

```

</details>

### Minimal code example

<details>
  <summary>Code sample</summary>

```dart
(no code required)
```

</details>

### Current Behavior

Currently this package and the *validators* package have a fixed dependency on `intl`.

### Expected Behavior

The dependency of `intl` should be `any` for both this package and *validators*.

### Steps To Reproduce

1. install latest flutter version (see doctor output)
2. try to build an ios app which has a dependency on this package
3. get compiler error about the `intl` dependency.

### Aditional information

**Using `any` for `intl` dependency is also suggested in the Flutter documentation.**

👀  https://docs.flutter.dev/accessibility-and-localization/internationalization#setting-up

**I cloned the repos and fixed the issue here:**

* https://github.com/bastibense/flutter_form_builder
* https://github.com/bastibense/form_builder_validators

Please fix this issue quickly, so I can remove the dependency to my fixed git repositories from my project again.

**Comment by deandreamatias** [comment]
Duplicated
