### ISSUE TITLE
FormBuilderCupertinoDateTimePicker no exist?

### ISSUE THREAD

**Issue by miguelangelflores1993** [flutter-form-builder-ecosystem/flutter_form_builder#1249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

10.0.0

### Flutter doctor

NA

### Minimal code example

NA

### Current Behavior

Try correcting the name to the name of an existing method, or defining a method named 'FormBuilderCupertinoDateTimePicker'

### Expected Behavior

exxist FormBuilderCupertinoDateTimePicker no exist?

### Steps To Reproduce

NA

**Comment by deandreamatias** [comment]
This don't exist. If added, it would be in https://github.com/flutter-form-builder-ecosystem/form_builder_cupertino_fields
