### ISSUE TITLE
[FormBuilderField]: TextField inside FormBuilderField unfocused when not valid with AutovalidateMode.onUserInteraction

### ISSUE THREAD

**Issue by icelija** [flutter-form-builder-ecosystem/flutter_form_builder#1258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

9.0.0

### Flutter doctor

<details>
  <summary>Flutter doctor</summary>

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.3.1 22E772610a darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.78.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

### Minimal code example

<details>
  <summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _formKey = GlobalKey<FormBuilderState>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: FormBuilder(
          key: _formKey,
          child: FormBuilderField<String>(
            name: 'username',
            autovalidateMode: AutovalidateMode.onUserInteraction,
            validator: (value) => value?.isNotEmpty == true ? null : 'Error',
            builder: (field) => TextField(
              onChanged: field.didChange,
              decoration: InputDecoration(
                errorText: field.hasError ? field.errorText : null,
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Current Behavior

When autovalidateMode on FormBuilderField is set to AutovalidateMode.userInteraction and validator returns an error, TextField is automatically unfocused.

### Expected Behavior

When autovalidateMode on FormBuilderField is set to AutovalidateMode.userInteraction, when validator returns an error, TextField should be still focused.

### Steps To Reproduce

1. Run the application on iOS or Android simulator or device.
2. Try to type something 
3. Delete the text to get validation error
4. Error: observe unfocused field.

**Comment by hashimsayed0** [comment]
I had a similar issue. What worked for me was not passing the autoValidateMode argument to the Form or FormBuilder function. I was passing them to the individual form builder items such as FormBuilderTextField.

**Comment by icelija** [comment]
@hashimsayed0 when using FormBuilderTextField widget AutovalidateMode.onUserInteraction works fine and doesn't unfocus textfield when field is not valid, but you can see in the code sample I have put, when I use FromBuilderField and plain TextField within then the textfield gets unfocused automatically when input is not valid which is not ok and it worked fine in previous version (8.0.0).

**Comment by ncuillery** [comment]
Me too, this issue is blocking me from upgrading to Flutter 3.10.

**Comment by icelija** [comment]
> Me too, this issue is blocking me from upgrading to Flutter 3.10.

You can still upgrade and use flutter_form_builder 8.0.0 by overriding intl dependency (to 0.18.0 or 0.18.1), I got the idea here and it works for me to use Flutter 3.10 and flutter_form_builder 8.0.0 which doesn't have the issue I described: https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/1230#issuecomment-1551209802

**Comment by ncuillery** [comment]
@icelija, I have tried that before posting and the `dependency_overrides` trick wasn't working. Thanks to your comment, I investigate a bit more and found out the reason.

I'm using melos https://github.com/invertase/melos which generates some `pubspec_overrides.yaml` files, this file takes precedence over the `dependency_overrides` key in `pubspec.yaml`, I have to run `melos bootstrap` so my intl override is copied into the `pubspec_overrides.yaml`.

Today I learn.

Thank you!

**Comment by hallmayer** [comment]
For me the onliest way was also the dependency override. For all who struggle these are my dependencies: 
```
intl: ^0.18.0
flutter_form_builder: ^8.0.0
form_builder_validators: ^8.0.0
```
and add this section to you pubspec.yaml after the dependencies 
`dependency_overrides:
  intl: ^0.18.0`

**Comment by godwinaden** [comment]
I am having the same issue. I must downgrade to 8.0.0

**Comment by holy-dev** [comment]
I'm getting this even in 8.0.0. It might be due to some incompatibility with SDK.

**Comment by deandreamatias** [comment]
HI @icelija
Here do you have 2 ways to create this widget and focus works fine:

1. Create a your own FormBuilderTextField setting a focus node, like [here](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/blob/e8410b39edba51a4b53e25c9416dbc54d018a674/lib/src/fields/form_builder_text_field.dart#L373)
2. Create a FocusNode on your widget state and assign to FormBuilderField and to TextField, like this
```dart
class _MyHomePageState extends State<MyHomePage> {
  final _formKey = GlobalKey<FormBuilderState>();
  final focus = FocusNode();  // Create here

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: FormBuilder(
          key: _formKey,
          onChanged: () {
            print(_formKey
                .currentState?.fields['username']?.effectiveFocusNode.hasFocus);
          },
          child: FormBuilderField<String>(
            name: 'username',
            focusNode: focus,  // Apply here
            autovalidateMode: AutovalidateMode.onUserInteraction,
            validator: (value) => value?.isNotEmpty == true ? null : 'Error',
            builder: (field) => TextField(
              focusNode: focus,  // Apply here
              onChanged: field.didChange,
              decoration: InputDecoration(
                errorText: field.hasError ? field.errorText : null,
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

Because of this little things, that we create a FormBuilderTextField and other fields with all setup

**Comment by icelija** [comment]
@deandreamatias thank you for your reply, works fine now, until version 9.0.0 my example worked even without passing the FocusNode to FormBuilderField and TextField but it makes sense as you described so I will close the ticket now.

I want to add that you made a great package and made handling all types of forms pretty easy and straightforward 🍻

**Comment by deandreamatias** [comment]
Nice to know!
