### ISSUE TITLE
full 24 hours picker 

### ISSUE THREAD

**Issue by TOMER628** [flutter-form-builder-ecosystem/flutter_form_builder#1278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

9.0.0

### What you'd like to happen

```Markdown
Hi.
I want to see on FormBuilderDateTimePicker all the hours, instead all hours in steps of 2 hour..

For example now we have 12,2,4...
I want 1,2,3 4

Can you please make an update for this please?

Regards,
Tomer.
```

**Comment by deandreamatias** [comment]
This is a issue for a native Flutter widget. Open a issue on their repository. Thanks
