### ISSUE TITLE
[General]: Clear button as internal solution for forms

### ISSUE THREAD

**Issue by khirsig** [flutter-form-builder-ecosystem/flutter_form_builder#1293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

9.1.0

### What you'd like to happen

```Markdown
Hello! :)

It would be great if the forms, that can use a clear button, would have an internal solution that could be set to on or off. That way it would be easier to handle the state of the form if it would be done internally.

It is already explained how to implement a clear button, but for a library this would be a good opportunity to offer an already implemented solution for this repeating problem.

As described in the material 3 styleguide: "Clear icons let users clear an entire input field. They appear only when input text is present." - If the input text is handled by the component itself, it would make sense that it also takes care of the clear feature.
```

**Comment by deandreamatias** [comment]
In the past this was implemented inside package, but had an extra effort to maintain and allow all possibilities, because is a big part of design implementation.
Currently can implement clear button like the examples [on readme](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder#implement-reset-clear-or-other-button-into-field)

**Comment by grundid** [comment]
Is there a thread I could follow up to understand the motivation to remove the clear icon from the library?
Right know only the DateRangePicker still has the allowClear property and the icon, so to be consistent one would have to remove it as well. 

We have an app with over 50 forms and maintaining the formKey and accessing it always feels like a pain. If the FormBuilder would be a read Builder and would pass the currentState as parameter to the builder method then yes, we could implement the clear icon on the developer side:

```dart
RealFormBuilder(
     builder: (BuildContext context, FormBuilderState currentState) {
          return Column(
            children: [
              FormBuilderTextField(
                name: "test",
                decoration: InputDecoration(
                    suffixIcon: IconButton(
                        onPressed: () {
                          currentState.fields["test"]?.didChange(null);
                        },
                        icon: Icon(Icons.clear))),
              ),
            ],
          );
        });
```

At the same time we could offer the library users some boiler plate code and create something like this:

```dart
class ClearButton extends StatelessWidget {
  final FormFieldState? fieldState;

  const ClearButton({super.key, required this.fieldState});

  @override
  Widget build(BuildContext context) {
    return IconButton(
        onPressed: () {
          fieldState?.didChange(null);
        },
        icon: Icon(Icons.clear));
  }
}
```

and then InputDecoration would look like this:
```dart
InputDecoration(suffixIcon: ClearButton(fieldState: currentState.fields["test"]))
```
AFAIK similar solutions are already discussed over here: #1132 

Nonetheless this still would not allow to show and hide the clear button depending on the content of the input field as described in the material style guide. For this to work only an integration into the library would be a suitable solution.

**Comment by grundid** [comment]
Would you accept a PR for a RealFormBuilder as show in the above comment? 

```dart
class RealFormBuilder extends StatelessWidget {
  final Widget Function(BuildContext context, FormBuilderState state) builder;

  const RealFormBuilder({super.key, required this.builder});

  @override
  Widget build(BuildContext context) {
    return FormBuilder(
      child: Builder(
        builder: (context) {
          FormBuilderState? state = FormBuilder.of(context);
          return builder(context, state!);
        },
      ),
    );
  }
}

```

**Comment by deandreamatias** [comment]
I don't sure about this change. I thing that need more discussion and separated topics for ClearButton and  FormBuilderState access.
Would can create a [discussions](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/discussions) with:
- Pro/Cons
- Use cases
- Examples of others packages/Flutter framework
- Issues related

**Comment by grundid** [comment]
Hi. We've created a discussion topic regarding the focus and keyboard input where we also demonstrate the usage of the clear icon. Please join the discussion and have a look at the demo/example project. 
Discussion: https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/discussions/1297

**Comment by deandreamatias** [comment]
Following our [maintenance philosophy](https://github.com/flutter-form-builder-ecosystem/.github/blob/main/MAINTENANCE_PHILOSOPHY.md), we do not see this as necessary or a priority at this time.
