### ISSUE TITLE
[Field name or General]: <title>

### ISSUE THREAD

**Issue by yjt1216** [flutter-form-builder-ecosystem/flutter_form_builder#1294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

7.7.0

### What you'd like to happen

```Markdown
flutter 项目 在输入框有输入内容的情况下，热更新一下后_formKey.currentState?.value内容TextEditingController中text内容一致
```

### Alternatives you've considered

```Markdown
flutter 项目 在输入框nameController.text有输入内容的情况下，热更新一下后_formKey.currentState?.value 中 value == {} and
 _formKey.currentState!.value['phone'] 中value["name"] = null
```

**Comment by deandreamatias** [comment]
Please open a new issue of type bug and fill and fields in English please
