### ISSUE TITLE
Error Widget is always showing

### ISSUE THREAD

**Issue by lovishnovelty** [flutter-form-builder-ecosystem/flutter_form_builder#1303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

9.1.1

### Platforms

- [X] Android
- [X] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Web
- [ ] Windows

### Flutter doctor

[✓] Flutter (Channel stable, 3.13.1, on macOS 13.5.2 22G91 darwin-arm64, locale en-NP)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.83.0)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached
      with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!

### Minimal code example

```dart
   FormBuilderTextField(
          name: 'login',
          initialValue: widget.initialValue,
          inputFormatters: widget.inputFormat,
          style: const TextStyle(
            fontSize: Dimens.text_size_default,
            textBaseline: TextBaseline.alphabetic,
          ),
          onSaved: widget.onSaved,
          textAlign: widget.textAlign ?? TextAlign.start,
          textCapitalization: widget.textCapitalization,
          autofocus: widget.autoFocus,
          obscureText: widget.obscureText,
          autovalidateMode: widget.autovalidateMode,
          validator: FormBuilderValidators.compose(validators!.isNotEmpty
              ? [
                  ...validators!,
                ]
              : []),
          onChanged: widget.onChanged,
          onTap: widget.onTap,
          readOnly: widget.readOnly,
          enabled: widget.enabled,
          controller: widget.controller,
          focusNode: widget.focusNode,
          onEditingComplete: () {
            FocusScope.of(context).requestFocus(widget.nextNode);
          },
          maxLines: widget.maxLines,
          maxLength: widget.maxLength,
          textInputAction: widget.textInputAction,
          keyboardType: widget.textInputType,
          decoration: InputDecoration(
            hintStyle: Theme.of(context).textTheme.bodySmall,
            counterText: '',
            contentPadding: const EdgeInsets.all(Dimens.spacing_large),
            prefixIcon: widget.prefixIcon == null
                ? null
                : IconButton(
                    icon: Icon(widget.prefixIcon),
                    onPressed: widget.onPrefixPressed,
                  ),
            suffixIcon: widget.suffixIcon == null
                ? null
                : IconButton(
                    icon: Icon(widget.suffixIcon),
                    onPressed: widget.onSuffixPressed,
                  ),
            hintText: widget.hintText,
            border: _generateBorder(widget.borderColor ?? AppColors.gray_light),
            focusedBorder: _generateBorder(AppColors.gray_dark),
            enabledBorder:
                _generateBorder(widget.borderColor ?? AppColors.gray_light),
            errorBorder: _generateBorder(AppColors.error),
            focusedErrorBorder: _generateBorder(AppColors.error),
            error: Row(
              children: [Text('icon'), Text('text')],
            ),
            
          ),
        ),
```

### Current Behavior

Even there is no error..the error widget is always shown.

### Expected Behavior

Show error widget only if there is error.

### Steps To Reproduce

1. Open App
2. Try to login
3. Donot type aything 
4. Error widget is already there

### Aditional information

when you delete the text and if text field is empty getting this error.

<img width="329" alt="Screenshot 2023-10-08 at 10 57 10" src="https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/assets/95479835/13d33273-71f3-4546-b6f6-2b5533c71960">

**Comment by deandreamatias** [comment]
Without a minimal example code, I can't reproduce the error. Please, try modify the example code to reproduce your error. Thanks
