### ISSUE TITLE
[FormBuilderRangeSlider]: Slider always at min value if initialValue is not set

### ISSUE THREAD

**Issue by grundid** [flutter-form-builder-ecosystem/flutter_form_builder#1305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

9.1.1

### Platforms

- [X] Android
- [X] iOS
- [ ] Linux
- [ ] MacOS
- [X] Web
- [ ] Windows

### Flutter doctor

<details>
  <summary>Flutter doctor</summary>

```bash

```

</details>

### Minimal code example

The code below is in the builder method so it is executed on each build. If initialValue is not set if will always set the value at min range. The field is unusable for the user.

```dart
          if (initialValue == null) {
            field.setValue(RangeValues(min, min));
          }

```

### Current Behavior

see above

### Expected Behavior

see above

### Steps To Reproduce

see above

**Comment by deandreamatias** [comment]
Solved by https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/pull/1331
