### ISSUE TITLE
[FormBuilderChoiceChip]: add showCheckmark option to choice chip

### ISSUE THREAD

**Issue by devon** [flutter-form-builder-ecosystem/flutter_form_builder#1317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

9.1.1

### What you'd like to happen

FormBuilderFilterChip has this option (`showCheckmark`), but FormBuilderChoiceChip doesn't.

It would be great if we could have `showCheckmark` for FormBuilderChoiceChip. Thanks.

**Comment by deandreamatias** [comment]
This will be nice and simple. Only add showCheckmark, and also add other properties, to [FormBuilderChoiceChip](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/blob/main/lib/src/fields/form_builder_choice_chips.dart)
