### ISSUE TITLE
I just wanna run isValid

### ISSUE THREAD

**Issue by iStarEternal** [flutter-form-builder-ecosystem/flutter_form_builder#1348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

1

### Platforms

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Web
- [ ] Windows

### Flutter doctor

-

### Minimal code example

-

### Current Behavior

-

### Expected Behavior

-

### Steps To Reproduce

-

### Aditional information

<img width="1257" alt="image" src="https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/assets/16184922/e4da85d5-0ec6-4d1b-9fa2-197f65aaeb96">

I just want to get isValid with out errorText, PLEASE!!!!

**Comment by iStarEternal** [comment]
<img width="732" alt="image" src="https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/assets/16184922/f0322004-3886-405d-bfc9-712d54159e80">

**Comment by lreardon** [comment]
I recently ran into the same issue, and created a pull request where I removed the errorText check from isValid. I'll link this issue to the PR
