### ISSUE TITLE
No named parameter with the name 'onPopInvoked'

### ISSUE THREAD

**Issue by KaranImaginationMedia** [flutter-form-builder-ecosystem/flutter_form_builder#1359]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Package/Plugin version

flutter_form_builder: ^9.2.0

### Platforms

- [ ] Android
- [X] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Web
- [ ] Windows

### Flutter doctor

<details>
  <summary>Flutter doctor</summary>

[✓] Flutter (Channel stable, 3.13.8, on macOS 14.0 23A344 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

</details>

### Minimal code example

<details>
  <summary>Code sample</summary>

```dart
Not able to run
```

</details>

### Current Behavior

Error

### Expected Behavior

Should be run

### Steps To Reproduce

N/A

**Comment by deandreamatias** [comment]
Please, add more information about this issue.
Currently, FormBuilder had the onPopInvoked property https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/blob/main/lib/src/form_builder.dart

**Comment by ManhBanh** [comment]
@deandreamatias  same here. I just build apk from the Macbook and it shows this error
![image](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/assets/52659954/7e265a04-3d35-4b2a-8592-713c0df637c4)

**Comment by wesleytoshio** [comment]
same here

**Comment by deandreamatias** [comment]
Ok.
This error is because onPopInvoked is a property for new version of Flutter 3.16.x, so on old version won't be works.
Use the version 9.1.1

**Comment by wesleytoshio** [comment]
> Ok. This error is because onPopInvoked is a property for new version of Flutter 3.16.x, so on old version won't be works. Use the version 9.1.1

Wouldn't it be better for you to fix it than asking us to downgrade flutter?

**Comment by deandreamatias** [comment]
> > Ok. This error is because onPopInvoked is a property for new version of Flutter 3.16.x, so on old version won't be works. Use the version 9.1.1
> 
> Wouldn't it be better for you to fix it than asking us to downgrade flutter?

You need downgrade package version, not Flutter.
If I remove onPopInvoked, this package won't be support for Flutter 3.16

**Comment by deandreamatias** [comment]
I release a new version 9.2.1 that update Flutter versions constraints to try avoid this error

**Comment by ManhBanh** [comment]
> I release a new version 9.2.1 that update Flutter versions constraints to try avoid this error

thank you  sir!

**Comment by aahilalwani25** [comment]
when i try to run `flutter --version`

it gives me result:
`flutter --version
Flutter 3.13.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2524052335 (11 months ago) • 2023-09-06 14:32:31 -0700
Engine • revision b8d35810e9
Tools • Dart 3.1.1 • DevTools 2.25.0`
