### ISSUE TITLE
[FormBuilderTextField]: Cannot swith to chinese keyborad with keyboardType: TextInputType.text

### ISSUE THREAD

**Issue by ginnyhuang** [flutter-form-builder-ecosystem/flutter_form_builder#1369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

9.1.0

### Platforms

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Web
- [ ] Windows

### Flutter doctor

<details>
  <summary>Flutter doctor</summary>

```
[√] Flutter (Channel master, 3.19.0-4.0.pre.1, on Microsoft Windows [版本 10.0.19045.4046], locale zh-TW)
    • Flutter version 3.19.0-4.0.pre.1 on channel master at C:\Software\Flutter\flutter_windows_3.10.6-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eeebee623e (6 weeks ago), 2024-01-09 22:25:40 -0500
    • Engine revision 1cf2e0a603
    • Dart version 3.4.0 (build 3.4.0-11.0.dev)
    • DevTools version 2.31.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\WishMobile\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\WishMobile\AppData\Local\Android\Sdk\;
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.6.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.6.33815.320
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.85.1)
    • VS Code at C:\Users\WishMobile\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.80.0

[√] Connected device (4 available)
    • Pixel 6 (mobile)  • adb-1C071FDF600A6H-w3OtAw._adb-tls-connect._tcp • android-arm64  • Android 14 (API 34)
    • Windows (desktop) • windows                                         • windows-x64    • Microsoft Windows [版本 10.0.19045.4046]
    • Chrome (web)      • chrome                                          • web-javascript • Google Chrome 121.0.6167.185
    • Edge (web)        • edge                                            • web-javascript • Microsoft Edge 121.0.2277.128

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

### Minimal code example

<details>
  <summary>Code sample</summary>

```
Column(
      children: [
        Text("FormBuilderTextField with TextInputType.text"),
        FormBuilderTextField(
          keyboardType: TextInputType.text,
          name: 'test1',
        ),
        SizedBox(
          height: 8,
        ),
        Text("TextField with TextInputType.text"),
        TextField(
          keyboardType: TextInputType.text,
        ),
        SizedBox(
          height: 8,
        ),
        Text("FormBuilderTextField with TextInputType.name"),
        FormBuilderTextField(
          keyboardType: TextInputType.name,
          name: 'test2',
        ),
        SizedBox(
          height: 8,
        ),
        Text("TextField with TextInputType.name"),
        TextField(
          keyboardType: TextInputType.name,
        ),
        SizedBox(
          height: 8,
        ),
        Text("FormBuilderTextField with TextInputType.emailAddress"),
        FormBuilderTextField(
          keyboardType: TextInputType.emailAddress,
          name: 'test3',
        ),
        SizedBox(
          height: 8,
        ),
        Text("TextField with TextInputType.emailAddress"),
        TextField(
          keyboardType: TextInputType.emailAddress,
        ),
        SizedBox(
          height: 8,
        ),
      ],
    )
```

</details>

### Current Behavior

Using FormBuilderTextField with TextInputType.text **cannot** swith keyboard language in Chinese, but using the origin TextField in flutter can switch keyboard language to Chinese.
I've try another TextInputType: TextInputType.mutiline, it has the same issue, too. 
On the contrary, TextInputType.name, TextInputType.emailAddress and TextInputType.streetAddress **can** swtich to Chinese keyboard both in FormBuilderTextField and TextField. ( But the keyboard still has some tiny different. )

The below is a sample film to show the FormBuilderTextField and TextField with TextInputType.text, TextInputType.name and TextInputType.emailAddress. 

https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/assets/6008083/4898fe2b-dd03-4612-bcb1-5fef84c67c65

### Expected Behavior

FormBuilderTextField with TextInputType.text can switch to chinese keyboard.

### Steps To Reproduce

1. With flutter version 3.19.0-4.0.pre.1 and dart version 3.4.0.
2. Test device ( Android OS ) need to enable language and keyboard of Traditional Chinese ( zh-TW ). I've try Japanese has same issue, too. Maybe any non-English language can reproduce this issue. 
3. Use following code to test FormBuilderTextField TextInputType.text. Click FormBuilderTextField to open keyboard and try to switch the language, and you will discover this issue.

### Aditional information

I face this issue after I upgrade the version of flutter and dart. The previous version I've used is 3.13.5 ( flutter ) and 3.1.2 ( dart ), and it work correct. I'm not sure witch flutter version will cause the issue. 
I've try to update this libs version to the newest ( 9.2.1 ) and it still not work.
It only appears in Android device. In iOS system it works fine. 

In the final, thanks for your reading and help! :)

**Comment by ginnyhuang** [comment]
> [yo1106](https://github.com/yo1106)
>Hello,
>
>I noticed that the input issue might be related to the enableSuggestions property being set to false. Have you tried setting enableSuggestions to true to see if it resolves the problem with the Chinese input?
>
>Enabling suggestions could allow the keyboard to provide predictive text and assist with the input in various languages, including Chinese.

Thanks a lot, it works! It saves my life. I didn't notice the parameter before.
It's magic that `enableSuggestions` related to keyboard language.

Here's the intorduction of this flag in Andoird: [TYPE_TEXT_FLAG_NO_SUGGESTIONS](https://developer.android.com/reference/android/text/InputType#TYPE_TEXT_FLAG_NO_SUGGESTIONS)
Maybe it's better to set default value `true` for `enableSuggestions`?

Again, thank you for your quick and accurate advice! :)

**Comment by Aashish-Dahal** [comment]
It works fine on my app after setting up `enableSuggestions` to true, Thank you 🙇  @yo1106 
<img width="329" alt="Screenshot 2024-03-19 at 9 46 53 AM" src="https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/assets/35824763/4be8900c-b5fc-4763-8f4c-3b8ad95ce463">

**Comment by netsesame2** [comment]
save my time, also.

**Comment by amotalles** [comment]
saved my day.

FormBuilderTextField(
            enableSuggestions: true,

**Comment by guppy-jonathan** [comment]
It saved my day.
Thanks

**Comment by kentomiya89** [comment]
me too 

thk!
