### ISSUE TITLE
FormBuilderDropdown onChanged fires twice during form Reset

### ISSUE THREAD

**Issue by Adam-Langley** [flutter-form-builder-ecosystem/flutter_form_builder#1371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

9.2.1

### Platforms

- [X] Android
- [X] iOS
- [ ] Linux
- [X] MacOS
- [ ] Web
- [X] Windows

### Flutter doctor

<details>
  <summary>Flutter doctor</summary>

```bash

```

</details>

### Minimal code example

<details>
  <summary>Code sample</summary>

```dart
FormBuilder(
    child: Column(
      children: [
        Builder(
          builder: (context) {
            return ElevatedButton(onPressed: (){
              FormBuilder.of(context)!.reset();
            }, child: Text('reset'));
          }
        ),
        FormBuilderDropdown(
          name: 'test', 
          initialValue: 'A', 
          items: [
            DropdownMenuItem(child: Text('A'), value: 'A'),
            DropdownMenuItem(child: Text('B'), value: 'B')
          ],
          onChanged: (value) {
            print('Changed value to $value');
          },
        ),
      ],
    ),
  ),
```

</details>

### Current Behavior

When resetting the form, the dropdowns "onChange" handler will fire twice in quick succession - one setting it to the "initialValue", then a second setting it back to the value it was before the reset button was clicked (essentially undoing the reset).

### Expected Behavior

When resetting the form, the "onChange" should fire only once, and the passed value should be the "initialValue".

### Steps To Reproduce

Using the above code snippet.

1. Run the code
2. Click the dropdown and change its value to "B"
3. Press the "reset" button

Note that it will not reset, but stay as "B", and the debug console will read

```
flutter: Changed value to A
flutter: Changed value to B
```

**Comment by Adam-Langley** [comment]
Additional information:

In my actual app (I'm assuming this is what's going on inside the demo code I provided too) - I have 4 FormBuilder fields.
2 * FormBuilderTextField
2 * FormBuilderDropdown

When I breakpoint the onChange, I can see that the form actually contains *6* field state objects - 2 for the text fields, and 4 for the dropdowns... it looks like for each dropdown there is a "FormBuilderDropdownState" and a "DropdownButtonFormFieldState".

When 'reset' is called on the FormBuilderDropdownState, it correctly fires onChanged and passes the initialValue.
However, when 'reset' is then called on the DropdownButtonFormFieldState this is when it resets it back to its current value.

I suspect this second state class isn't supposed to be in the fields collection - as it's just a double-up, one that breaks the functionality at that.

**Comment by RanjanKiran707** [comment]
> Additional information:
> 
> In my actual app (I'm assuming this is what's going on inside the demo code I provided too) - I have 4 FormBuilder fields. 2 * FormBuilderTextField 2 * FormBuilderDropdown
> 
> When I breakpoint the onChange, I can see that the form actually contains _6_ field state objects - 2 for the text fields, and 4 for the dropdowns... it looks like for each dropdown there is a "FormBuilderDropdownState" and a "DropdownButtonFormFieldState".
> 
> When 'reset' is called on the FormBuilderDropdownState, it correctly fires onChanged and passes the initialValue. However, when 'reset' is then called on the DropdownButtonFormFieldState this is when it resets it back to its current value.
> 
> I suspect this second state class isn't supposed to be in the fields collection - as it's just a double-up, one that breaks the functionality at that.
> 
> <img alt="image" width="740" src="https://private-user-images.githubusercontent.com/16373742/306903650-579c4265-47c4-449a-be1c-b18a5363db5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMjI1MjAsIm5iZiI6MTcyNjMyMjIyMCwicGF0aCI6Ii8xNjM3Mzc0Mi8zMDY5MDM2NTAtNTc5YzQyNjUtNDdjNC00NDlhLWJlMWMtYjE4YTUzNjNkYjVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDEzNTcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwOTM5MDZmYzlmMjVmYTkyYTFjY2ViNzJmZDMxOWNiMDg0YTgyMzEzODAyNWU0OTg2NDM0ZTQxMjU5Y2FiZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.21PylZnzODQllwzvTWr9ErI8s8eyQv7MWOvK721EykA">

Yeah but DropdownButtonFormField also extends FormField, In FormField's build function we are registering this field. So even this gets registered

If we comment out the reset function for DropdownButtonFormFieldState it works.
