### ISSUE TITLE
[FormBuilderTextField]: Add missing TextField properties.

### ISSUE THREAD

**Issue by RepliedSage11** [flutter-form-builder-ecosystem/flutter_form_builder#1416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

9.4.0

### What you'd like to happen

```Markdown
FormBuilderTextField is missing some of the TextField properties. These properties should be added to the FormBuilderTextField constructor and passed to the TextField.

These are
canRequestFocus
clipBehavior
cursorErrorColor
cursorOpacityAnimates
enableIMEPersonalizedLearning
groupld
ignorePointers
onAppPrivateCommand
onChanged
onTapAlwaysCalled
scribbleEnabled
selectionControls
statesController
toolbarOptions
undoController
```

### Alternatives you've considered

```Markdown
Implement a complete copy of FormBuilderTextField using FormBuilderField with the missing properties.
```

**Comment by deandreamatias** [comment]
Thanks for report
If you can open a PR to add this, I will glad to review and merge.

**Comment by RepliedSage11** [comment]
Submitted a [PR](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/pull/1417)

**Comment by deandreamatias** [comment]
To generate a new version, please update pubspec and changelog. After merge this, I create a tag and automatically push to pub.dev
