### ISSUE TITLE
Add Cupertino examples

### ISSUE THREAD

**Issue by ghost** [flutter-form-builder-ecosystem/flutter_form_builder#22]
Hi is there a Cupertino example?

**Comment by danvick** [comment]
Not just yet. But we can plan for that in future releases

**Comment by namiwang** [comment]
@danvick 

Hi! We're working on integrating `flutter_form_buider` with https://github.com/aqwert/flutter_platform_widgets/, to implement cupertino text fields.

Would you guys think this is an acceptable approach? Would like to contribute.

**Comment by nuzelac** [comment]
@namiwang do you have any repo/fork with `flutter_platform_widgets` integration?

**Comment by dmitrykuznetsovdev** [comment]
+

**Comment by deandreamatias** [comment]
This package in this momento don't support Cupertino fields.
In future, if make sense, we add some cupertino style fields.

The only widget that exist with Cupertino style, is `FormBuilderCupertinoDateTimePicker` in https://github.com/flutter-form-builder-ecosystem/form_builder_extra_fields

**Comment by deandreamatias** [comment]
I created a [new package](https://pub.dev/packages/form_builder_cupertino_fields) for only Cupertino fields
