### ISSUE TITLE
[FormBuilderDateTimePicker] Add custom suffixicon

### ISSUE THREAD

**Issue by Dreamersoul** [flutter-form-builder-ecosystem/flutter_form_builder#248]
allow the addition of a suffix icon when value is null and change it to clear icon when the value is set,
setting the suffixIcon from input decoration overrides the clear icon

**Comment by Dreamersoul** [comment]
i have created a PR jifalops/datetime_picker_formfield#88 to help with this once merged ill create a PR here.

**Comment by sumitbhanushali** [comment]
@Dreamersoul @danvick 
also, can we remove the resetIcon when in readOnly mode?

**Comment by Dreamersoul** [comment]
I really wish we can but the maintainer seems inactive

**Comment by danvick** [comment]
@sumitbhanushali @Dreamersoul 
I feel like because of this, our best recourse would be instead of having the package as a dependency we could fork it to make improvements or have a copy of the widget as part of the repo, where we could make changes as needed.

**Comment by Dreamersoul** [comment]
I agree! I am currently busy once I have some free time I'll issue a pull request and add the widget

**Comment by danvick** [comment]
I would really appreciate a PR because currently most of my time spent on this repo is focused on writing the next major version.
