### ISSUE TITLE
[FormBuilderCheckbox] using custom checkbox icon

### ISSUE THREAD

**Issue by brizaldi** [flutter-form-builder-ecosystem/flutter_form_builder#249]
Please add the ability to change FormBuilderCheckbox checkbox icon

**Comment by danvick** [comment]
This looks like an interesting idea, I'll consider having it added to the package.

Meanwhile, PRs are always welcome ;-) - if you have time.

Cheers!

**Comment by Siqlain-Hanif** [comment]
@danvick i am looking to add the checkboxShape property of CheckBoxListTile in FormBuilderCheckbox that take OutlinedBorde. Do you have any other requirement for this to work on ?

**Comment by Siqlain-Hanif** [comment]
Oh yeah i think the custom active and inactive icons makes more sense as the border of checkbox can be changed through theming.

**Comment by Siqlain-Hanif** [comment]
@danvick my attempt to custom icons for the checkbox

**Comment by Siqlain-Hanif** [comment]
https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/pull/1131

**Comment by Siqlain-Hanif** [comment]
https://user-images.githubusercontent.com/53166182/198714669-43225071-6539-4ac7-8d16-bd7749fad019.mp4

**Comment by deandreamatias** [comment]
As of [this](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/pull/1131#issuecomment-1295889701) and following comments, we decide no implement this feature. Sorry for that
