### ISSUE TITLE
Restrict Non English Characters | Assistance Required

### ISSUE THREAD

**Issue by NiranjanShah** [flutter-form-builder-ecosystem/flutter_form_builder#384]
How to avoid non English Characters in form field.

Like in India we have Hindi(devangiri) , so want to restrict user to input only English Character.

Tried with FormBuilderValidators.pattern("([^\u0900-\u097F]|\w)+"), however it is accepting **non English Characters**

**Comment by deandreamatias** [comment]
You can use [TextInputFormatter](https://stackoverflow.com/questions/50123742/how-to-use-inputformatter-on-flutter-textfield) to do this.
The regex pattern I don't know how to do it, but should be exist a solution in internet
