### ISSUE TITLE
Add day of the week picker

### ISSUE THREAD

**Issue by Prn-Ice** [flutter-form-builder-ecosystem/flutter_form_builder#409]
Would like to know if you have an included day of week selector, something that only displays Monday - Sunday. And also a day of month selector for days in a month eg 1 - 30.

**Comment by awhitford** [comment]
Not specifically, but I've built a Weekday selector by just using a FormBuilderCheckboxGroup or FormBuilderRadioGroup.

Here is a tip on generating the Weekdays (localized):
```dart
      final weekdayFormat = DateFormat.E();
      // Note that 2018-01-01 is special because it is a Monday,
      // so replacing the date with the weekday ordinal produces
      // the correct value from the formatter.
      ...
      final weekdays = List.generate(7,
        (weekday) => Text(weekdayFormat.format(DateTime(2018, 1, weekday))),
      );
```

**Comment by deandreamatias** [comment]
Hi @Prn-Ice 
This is a nice feature but I don't know if a feature with a lot use. How _awhitford_ says, you can create easily a CheckboxGroup or RadioGroup with options and your own style.
Create this field means idealize a design and now don't exist a pattern (Material or Cupertino) for a week day selector
