### ISSUE TITLE
state didChange for FormBuilderRadioGroup not work

### ISSUE THREAD

**Issue by FourLeafTec** [flutter-form-builder-ecosystem/flutter_form_builder#475]
I try to set value to a FormBuilderRadioGroup,so i use 
```
_fbKey.currentState.fields["ipAssignment"].currentState.didChange("DHCP");
```
to do this. it not work on ui,but the _fbKey.currentState.fields["ipAssignment"].currentState.value change to DHCP

but it works for a FormBuilderDropdown and also works for FormBuilderRadio

**Comment by SachinTanpure** [comment]
I am also facing similar issue for radio group. Value is properly set but on UI radio option is not reflected.

**Comment by myThorsten** [comment]
I'm facing this issue with **FormBuilderChipsInput**.

Callling `formKey.currentState.fields[formKeyEncounterIdContacts].didChange(contactDisplays);` does result in **onChanged** to be called, but the UI still shows the old state.

**Comment by deandreamatias** [comment]
This still an issue?

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/new/choose)
