### ISSUE TITLE
FormBuilderTypeAhead event when field is cleared.

### ISSUE THREAD

**Issue by danielweil** [flutter-form-builder-ecosystem/flutter_form_builder#532]
Is there any way to trigger an event when the field is cleared?
I tried using onChange and checking if value is empty but OnChange only triggers when I select an option from the suggestions.

It would be a awesome if there was a clear icon on the right, and when cleared (or manually cleared), a event would be triggered. 
Is it possible?

Thanks!

**Comment by awhitford** [comment]
You can add a clear icon yourself by specifying an `InputDecoration` with a `suffixIcon`.
```dart
                  decoration: InputDecoration(
                    suffixIcon: IconButton(
                      icon: const Icon(Icons.cancel),
                      onPressed: () {
                        ...
                      }
                  ),
```

**Comment by danielweil** [comment]
Hey, Thanks Antonio! 

I would still need an event to trigger when the field is emptied. (For when the user removes the text manually)

**Comment by danielweil** [comment]
I implemented what Anthony said. Still would love an event trigger on field empty.
Besides that, Is there any way to hide suggestion on a possible clear? So if I press the cancel icon, the suggestion Box does not come up.

Thanks for your help!

**Comment by awhitford** [comment]
Please note that this project provides a thin wrapper around [flutter_typeahead](https://pub.dev/packages/flutter_typeahead).  My immediate suspicion is that you may want to direct functionality requests for that specific widget to that specific project.

> I would still need an event to trigger when the field is emptied. (For when the user removes the text manually)

It sounds like you want an `onChange` handler specifically for when the _query_ text changes.  That sounds like something that the widget will need to provide -- this framework wouldn't be able to provide that directly.

> Is there any way to hide suggestion on a possible clear? So if I press the cancel icon, the suggestion Box does not come up.

Not totally sure without trying, but you may be able to control this with your `findSuggestions` function -- what if you return an empty list or null?

**Comment by danielweil** [comment]
> Please note that this project provides a thin wrapper around [flutter_typeahead](https://pub.dev/packages/flutter_typeahead). My immediate suspicion is that you may want to direct functionality requests for that specific widget to that specific project.
> 
> > I would still need an event to trigger when the field is emptied. (For when the user removes the text manually)
> 
> It sounds like you want an `onChange` handler specifically for when the _query_ text changes. That sounds like something that the widget will need to provide -- this framework wouldn't be able to provide that directly.
> 
> > Is there any way to hide suggestion on a possible clear? So if I press the cancel icon, the suggestion Box does not come up.
> 
> Not totally sure without trying, but you may be able to control this with your `findSuggestions` function -- what if you return an empty list or null?

It does not work, as I want the suggestion to show when the query is empty. I want to hide it when I clear the query using the suffixIcon.

**Comment by deandreamatias** [comment]
This still an issue?

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)
