### ISSUE TITLE
[New feature] Property to know if the form has changes

### ISSUE THREAD

**Issue by nipunasudha** [flutter-form-builder-ecosystem/flutter_form_builder#617]
How can I know the form is dirty. I'm aware of the onChange listener but it currently brakes the signature field (#457). I'm looking for a bool for example, `isDirty` in the form builder state.

**Comment by THALLIVA** [comment]
Did we find a solution or any workaround for this issue? As it's basic functionality, I think it should be taken on priority.

**Comment by quanglefed** [comment]
Hi, any update for this?

**Comment by nipunasudha** [comment]
I only requested this feature because `onChange` was broken at the time. The question "Does the form have any changes" feels like a little bit subjective, since not everybody want to detect ALL the changes to the form. So I suggest you to implement your own `isDirty` flag using the `onChange` callback.

**Comment by deandreamatias** [comment]
A solution that I think is compare initialValue with instantValue. If is different, has changes

**Comment by deandreamatias** [comment]
I create this solution to get new changes
```dart
  final formKey = GlobalKey<FormBuilderState>();

  /// Get only the changed values.
  /// Compare the initial value and actual value of form and get the difference
  ///
  /// By default, use saved values [formValues] as actual value
  Map<String, dynamic> getChangedValues({bool useInstantValues = false}) {
    final _formValues = useInstantValues
        ? formKey.currentState?.instantValue ?? {}
        : formKey.currentState?.value ?? {};
    final _initialValues = formKey.currentState?.initialValue ?? {};
    final _changedValues = <String, dynamic>{};

    for (var entry in _formValues.entries) {
      if (_formValues[entry.key] != _initialValues[entry.key]) {
        _changedValues[entry.key] = entry.value;
      }
    }

    return _changedValues;
  }
```

**Comment by BenjiFarquhar** [comment]
@deandreamatias Where is `instantValue`?

**Comment by deandreamatias** [comment]
@BenjiFarquhar I think that was add in 7.0.0+ versions

**Comment by deandreamatias** [comment]
Can test this on [pre-release 9.0.0-dev.1](https://pub.dev/packages/flutter_form_builder/versions/9.0.0-dev.1)
