### ISSUE TITLE
[Feature request] Location picker

### ISSUE THREAD

**Issue by angwandi** [flutter-form-builder-ecosystem/flutter_form_builder#651]
Is there a location picker here?

**Comment by danvick** [comment]
We have a [separate repo](https://pub.dev/packages/form_builder_map_field/versions/1.0.0-alpha.1) for this, though it's not as refined as I'd like to have it.

**Comment by mdeandrea-mrmilu** [comment]
Can be close this issue?

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/new/choose)
