### ISSUE TITLE
FormBuilderTextField changes InputBorder in error state

### ISSUE THREAD

**Issue by mattf80** [flutter-form-builder-ecosystem/flutter_form_builder#665]
Hi,

I have the following text field:

```
              FormBuilderTextField(
                name: 'email',
                validator: FormBuilderValidators.required(context),
                decoration: InputDecoration(labelText: 'Email address'),
              ),
```

and in my app's theme am defining the InputBorders for each state:

```
InputDecorationTheme _inputDecorationTheme = InputDecorationTheme(
  focusColor: Colors.deepOrange.shade200,
  
  focusedBorder: OutlineInputBorder(
    borderSide: BorderSide(color: Colors.deepOrange.shade200),
  ),
  enabledBorder: OutlineInputBorder(
    borderSide: BorderSide(color: Colors.white),
  ),
  errorBorder: OutlineInputBorder(
    borderSide: BorderSide(color: Colors.red),
  ),
);
```

However I've noticed that if the form field is in a validator error state _and_ has focus then the appearance defaults to the standard Material input type (no border, text field underlined). Is this a bug or am I missing a setting somewhere? In the image below both fields have failed validation and the Password field has focus:

![image](https://user-images.githubusercontent.com/11922558/103410688-5d5b2800-4b64-11eb-9fcc-9c645e597847.png)

Thanks,

**Comment by dunika** [comment]
I am also seeing this issue. Has anyone had a chance to look into it?

**Comment by mnorhamizan** [comment]
This is still happening. Any update?

**Comment by deandreamatias** [comment]
Hi @mattf80 
Please can help to verify this error? I need that you complete this template. You can replay answer in this thread or edit the original issue details and respond by tagging me.

Thanks a lot

```markdown
## Environment

**Package name:**  flutter_form_builder
**Package version:**  <!-- Add branch if necessary -->
**Platform:** <!-- iOS, Android, Web, etc -->
**Device information:**  <!-- Manufacturer and model -->

## Description

**Expected behavior:**

**Current behavior:**

## Steps to reproduce

1. This
2. Than that
3. Then

## Images <!-- if available, else delete -->  

## Stacktrace/Logcat <!-- if available, else delete -->
```

**Comment by aisjac** [comment]
Have to use another property **border** along with **focusedBorder**, **enabledBorder** and **errorBorder**
