### ISSUE TITLE
[FormBuilderDropdown] Add multiple select option

### ISSUE THREAD

**Issue by Kalyanb447-github** [flutter-form-builder-ecosystem/flutter_form_builder#671]

**Comment by deandreamatias** [comment]
This still a issue?

**Comment by Marigi-tech** [comment]
Was this ever solved?

**Comment by deandreamatias** [comment]
No. Need create this widget and integrate a FormBuilderField

**Comment by deandreamatias** [comment]
Maybe can get [this implementation](https://github.com/TaimoorHassan/multiselect) and adapt to this package

**Comment by deandreamatias** [comment]
Currently we will focus on maintain the active fields and no add any more.
If someone want this feature, can implement a [custom field](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder#building-your-own-custom-field) or add a field on [form_builder_extra_fields](https://github.com/flutter-form-builder-ecosystem/form_builder_extra_fields)
