### ISSUE TITLE
Some of the FormBuilderValidator types may be wrong

### ISSUE THREAD

**Issue by Sylphide** [flutter-form-builder-ecosystem/flutter_form_builder#685]
Hi,

For templated inputs, validators require to have the type 

`String Function(List<T>) validator`

But some of the built-in validators have the type

`String Function(String) validator`

i.e FormBuilderValidators.minLength

I was trying to use them in a FormBuilderChipsInput but ran into a typing problem.
Am I doing something wrong or is it not intended?

**Comment by deandreamatias** [comment]
This still an issue?

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)

**Comment by kirqe** [comment]
I think it still exists -_-

```
FormBuilderTextField(
validator: FormBuilderValidators.compose([
```
