### ISSUE TITLE
v3 to v4 migration - formBuilder initialValue breaking change

### ISSUE THREAD

**Issue by danielwalczak** [flutter-form-builder-ecosystem/flutter_form_builder#705]
Behavior of formBuilder initialValue did changed and its not mentioned in the Readme. 

In v3 I used to add more information to the initial values which where not actual form fields, they meant to be send with rest values to the api.
```
initialValue: {
   id: 123, <- this is not a field
   type: 'human', <- this is not a field
   name: 'example' <-this is a form field
```
then all the values where return in `_formKey.currentState.value`
```
_onSubmit() {
    if (_formKey.currentState.saveAndValidate()) {
      Map<String, dynamic> values = _formKey.currentState.value;
      ...
      }
}
```

in v4 `id` and `type` is not return anymore form `_formKey.currentState.value` only `name`

so to make it works I don't add additional fields into the initialValues.

For me it's a little bit weird behavior, it's possible that this will create issues with forms which are build in multiple steps/sections, or other things.

**Comment by Falamarcao** [comment]
> For me it's a little bit weird behavior, it's possible that this will create issues with forms which are build in multiple steps/sections, or other things.

Confirmed!

I'm using IndexedStack for build a multiple steps form with some fields like datastamp and I'm not more able to initialize a value that is not a field on initialValue parameter from FormBuilder. I'm looking now for insert the value by other means. This is really odd for me too. It was a easy way to get the time which the form started being filled.

**Comment by guenth39** [comment]
I also have the problem. Especially for ids etc. this was always very helpful. Please activate again.

**Comment by deandreamatias** [comment]
This still an issue?
