### ISSUE TITLE
FormBuilderDateTimePicker onConfirm is not being triggered 

### ISSUE THREAD

**Issue by AbanoubNassem** [flutter-form-builder-ecosystem/flutter_form_builder#709]
`FormBuilderDateTimePicker` `onConfirm` is not being triggered using the latest version

**Comment by deandreamatias** [comment]
This still an issue?

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)
