### ISSUE TITLE
FormBuilerChipsInput issue (initialValue & patchValue)

### ISSUE THREAD

**Issue by harlanx** [flutter-form-builder-ecosystem/flutter_form_builder#712]
Assigning the initialValue in the main FormBuilder Widget using a map doesn't assign any values to the FormBuilderChipsInput Widget. As a workaround, I just assigned the initialValue to the Chips Input widget instead.
Also currentState.patchValue doesn't work if an initialValue is specified (initial value just stays there if specifying a new list for the input field or doesn't clear it's field by assigning an empty list for the input field).

Just an update on this.
currentState.reset() doesn't also revert to the initialvalue provided.
Last update on my issue.
Values can actually be changed but the UI is not being updated.

**Comment by SubutaDan** [comment]
Hi @harlanx , I have run into a similar issue.  In my case too reset is clearing the value in currentState but leaving the chips in place on the screen.  Have you made any progress on resolving this?  Thanks. -Dan

**Comment by harlanx** [comment]
Hello @SubutaDan . I was able to achieve the field clearing that reflects on UI but have not yet tested adding values or brining back it to initial values.

I have created a 
ChipsInputState _chipsState = ChipsInputState();
Then passed it on the 
chipBuilder: (context, state, value) {
_chipsState = state;
....}

then on my clear field method I just need to do
formBuilderKey.currentState.fields['selectedContacts'].value.forEach((val){
                _chipsState.deleteChip(val);
              });

**Comment by harlanx** [comment]
Hello @SubutaDan . I was able to achieve the field clearing that reflects on UI but have not yet tested adding values or brining back it to initial values.

First I imported
import 'package:flutter_chips_input/flutter_chips_input.dart' (this is from the dependency of formbuilder package);
then created
ChipsInputState _chipsState = ChipsInputState();
Then assign a state from the FormBuilerChipsInput
chipBuilder: (context, state, value) {
_chipsState = state;
....}

then on my clear field method I just need to do
formBuilderKey.currentState.fields['selectedContacts'].value.forEach((val){
                _chipsState.deleteChip(val);
              });

**Comment by SubutaDan** [comment]
Thanks very much, @harlanx . I have started experimenting with your technique and so far it is working for me.  -Dan

**Comment by deandreamatias** [comment]
This still an issue?

**Comment by deandreamatias** [comment]
Maybe related with #1052

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)
