### ISSUE TITLE
FormBuilderCheckboxGroup Validation

### ISSUE THREAD

**Issue by SM2DevLLC** [flutter-form-builder-ecosystem/flutter_form_builder#713]
Is there an example anywhere of how to use validation on `FormBuilderCheckboxGroup`? Using `FormBuilderValidators.compose` throws the error `Couldn't infer type parameter 'T'.` and there doesn't seem to be examples anywhere.

**Comment by RodrigoSMarques** [comment]
Same problem here. I couldn't understand how to do the validation.

**Comment by bawa-ra** [comment]
same

**Comment by FatihAydin52** [comment]
same

**Comment by codeorelse** [comment]
@SM2DevLLC did you find a way around this, by any chance?

**Comment by igiazlas** [comment]
Is there any update on this issue?

**Comment by codeorelse** [comment]
For now I made a workaround for a manual validation:

```
validator: (List<dynamic> answers) {
              if (answers.length == 0)
                return '<Your error here>';
              return null;
            },
```

Not the best solution, but for now this is a working workaround.

**Comment by deandreamatias** [comment]
This still an issue?

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)

**Comment by kirqe** [comment]
@deandreamatias it hasn't been fixed and should be reopened
