### ISSUE TITLE
Cupertino style fields

### ISSUE THREAD

**Issue by diegoalex** [flutter-form-builder-ecosystem/flutter_form_builder#718]
Is there any way to style the fields inline as Cupertino way?

Something like that:
![image](https://user-images.githubusercontent.com/3237570/108779938-6eae2880-7546-11eb-979a-be483a940df2.png)

Thanks

**Comment by deandreamatias** [comment]
You can create your own fields with `FormBuilderField`

Is a hard thing create new components only for cupertino style. One option would be add this styles for existent components, but is a feature that don't will be add in the current roadmap

**Comment by deandreamatias** [comment]
Currently we don't develop support to Cupertino design fields

**Comment by deandreamatias** [comment]
I refactor this package and created a new repository to only Cupertino fields. Right now only has a few fields, but will increase on future
https://github.com/flutter-form-builder-ecosystem/form_builder_cupertino_fields
