### ISSUE TITLE
Moving to sound null safety - Because flutter_form_builder 5.0.0-alpha.1 depends on signature ^3.2.1 and no versions of flutter_form_builder match >5.0.0-alpha.1 <6.0.0, flutter_form_builder ^5.0.0-alpha.1 requires signature ^3.2.1.

### ISSUE THREAD

**Issue by thecocce** [flutter-form-builder-ecosystem/flutter_form_builder#732]
Hi, i tried to move to sound null safety.

*  signature: ^4.0.0-nullsafety
*  image: ^3.0.0-nullsafety.0
*  image_picker: ^0.7.2
*  flutter_form_builder: ^5.0.0-alpha.1

**Comment by psrcek** [comment]
Same here, tried to run `dart pub upgrade --null-safety` and got this:

Because flutter_form_builder >=5.0.0-alpha.1 depends on signature ^3.2.1 which depends on image ^2.1.12, flutter_form_builder >=5.0.0-alpha.1 requires image ^2.1.12.
So, because *[app]* depends on both flutter_form_builder 5.0.0-alpha.1 and image >=3.0.0-nullsafety.0, version solving failed.

**Comment by danvick** [comment]
Hi all,
Kindly note that this package cannot implement null safety - for now at least - since some of the packages we depend on haven't implemented null safety yet.

We are also excited about null-safety and would like to have it implemented in the package soon.

**Comment by psrcek** [comment]
You can still import legacy libraries in null safe code, just add a `// ignore: import_of_legacy_library_into_null_safe` above the legacy import and your linter and compiler won't care.

**Comment by nipunasudha** [comment]
> You can still import legacy libraries in null safe code, just add a `// ignore: import_of_legacy_library_into_null_safe` above the legacy import and your linter and compiler won't care.

This method is not recommended by flutter, and certainly should not be done in a major package like flutter_form_builder imho

**Comment by deandreamatias** [comment]
This still an issue?

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)
