### ISSUE TITLE
after comming a setState() called after dispose(): _FormBuilderTextFieldState#0ebf9(lifecycle state: defunct, not mounted)

### ISSUE THREAD

**Issue by Kalyanb447-github** [flutter-form-builder-ecosystem/flutter_form_builder#737]
setState() called after dispose(): _FormBuilderTextFieldState#0ebf9(lifecycle state: defunct, not mounted)

**Comment by deandreamatias** [comment]
This still an issue?

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)
