### ISSUE TITLE
FormBuilderTextField  onChange callback behavior

### ISSUE THREAD

**Issue by quanglefed** [flutter-form-builder-ecosystem/flutter_form_builder#747]
Hi,

Version: 4.2.0 
Current behavior: The onChange behavior of FormBuilderTextField is emitted when focusing. 
Expected behavior: The onChange behavior of FormBuilderTextField is emitted when text change only.
Btw, can i know about status of #617 . I think it's a basic status of the form. And do we have any way to validate only when the field is dirty?

Thanks!

**Comment by deandreamatias** [comment]
This still an issue?

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)
