### ISSUE TITLE
  FormBuilderDateTimePicker onChanged sending year 1970 on flutter_form_builder: ^5.0.0-alpha.1

### ISSUE THREAD

**Issue by m-j-g** [flutter-form-builder-ecosystem/flutter_form_builder#751]
flutter_form_builder: ^5.0.0-alpha.1

When changing the date on FormBuilderDateTimePicker you will receive an onChanged event with the correct date.  And then you will receive multiple additional onChanged events with the correct month and day, but the year will be 1970.

**Comment by deandreamatias** [comment]
This still an issue?
