### ISSUE TITLE
FormBuilderSegmentedControl textStyle missing?

### ISSUE THREAD

**Issue by chagaj** [flutter-form-builder-ecosystem/flutter_form_builder#758]
Hello,

Firstly thank you for the great work you've done developing and maintaining this package. 

I recently upgraded this package and found that the textStyle attribute is missing for FormBuilderSegmentedControl. 

Could anyone point me in the direction of how I could change the textStyle of the text contained within each selection box of the FormBuilderSegmentedControl please?

Thanks in advance.

**Comment by deandreamatias** [comment]
This still an issue?

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)
