### ISSUE TITLE
onChanged does not fire for fields added programmatically after initial build after v5.0.0

### ISSUE THREAD

**Issue by andrewjallenuoft** [flutter-form-builder-ecosystem/flutter_form_builder#763]
After version 5.0.0, the onChanged function does not fire on fields that are added programmatically after the initial build.

For example, the user may hit a button that adds a new FormBuilderField. After calling setState, the new field will appear, but the onChanged callback won't be triggered on it ever.

`ElevatedButton(
  onPressed: () => setState(() => fields++),
  child: Text("Add field"),
)`

...

`for (int i=0; i< fields; i++) ...[
  FormBuilderTextField(
     name: 'units${i + 1}',
     controller: _unitController,
     onChanged: (s) {
         // Never triggered
     },
     validator: FormBuilderValidators.required(context),
  ),
]`

This does not occur in version 4.2.0. Changing from version 4.2.0 to version 5.0.0, without making any other changes, will result in onChanged never being triggered.

**Comment by mammba01012018** [comment]
Same issue after updating to 5.0. onChanged does not fire

**Comment by deandreamatias** [comment]
This still an issue?

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)
