### ISSUE TITLE
Request Enhancement

### ISSUE THREAD

**Issue by nousath** [flutter-form-builder-ecosystem/flutter_form_builder#770]
Hai all, i request add some features like

1. Asynchronous Validators
2. Focus and Scrolling
3. customize error messages
4. Form submit validator fields Errors return Like **Map** 
5. onSubmitted focus fields

**Comment by mammba01012018** [comment]
Same. Would be great if they would add these specially Asynchronous Validators and focus fields.

**Comment by deandreamatias** [comment]
@nousath Can create separated issue for this features? Thanks
