### ISSUE TITLE
How can I FormBuilderFilterChip validator max select

### ISSUE THREAD

**Issue by saeed1366** [flutter-form-builder-ecosystem/flutter_form_builder#780]
How can I FormBuilderFilterChip validator limit max select

**Comment by avp90** [comment]
You can use `maxChips` property on `FormBuilderFilterChip`.

**Comment by deandreamatias** [comment]
> You can use `maxChips` property on `FormBuilderFilterChip`.

This comment solve your question @saeed1366 ? If yes, please close this issue

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)
