### ISSUE TITLE
iOS Hardware Keyboard Support

### ISSUE THREAD

**Issue by alexmarkley** [flutter-form-builder-ecosystem/flutter_form_builder#793]
I'm using `flutter_form_builder` version 6.0.0 (thanks again for updating it!).

When editing a multiline text field using a hardware keyboard on iOS, I've noticed that the up and down arrow keys are not behaving as expected.

Expected behavior: Up and Down arrows should navigate the cursor to the line above or below.

Observed behavior: Up and Down arrows cause the cursor to move to the left and the right.

**Comment by deandreamatias** [comment]
This still an issue?

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/new/choose)
