### ISSUE TITLE
FormbuilderDatepicker Unhandled Exception: A FocusNode was used after being disposed.Once you have called dispose() on a FocusNode, it can no longer be used

### ISSUE THREAD

**Issue by zozeei** [flutter-form-builder-ecosystem/flutter_form_builder#795]

**Comment by jayjah** [comment]
[addressed here](https://github.com/danvick/flutter_form_builder/pull/799)

**Comment by jayjah** [comment]
@zozeei this issue can be closed, till PR got merged and update is available, even on pub.dev

**Comment by YouSour** [comment]
i face this problem too , anyone fixed it yet ?

**Comment by deandreamatias** [comment]
This still an issue?

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)
