### ISSUE TITLE
[FormBuilderTextField] Add allowClear

### ISSUE THREAD

**Issue by fehernyul** [flutter-form-builder-ecosystem/flutter_form_builder#798]
Exactly the same like in FormBuilderDropdown.
I tried to make this, but the looking what it displays so wierd.

![image](https://user-images.githubusercontent.com/25593792/118264892-b21a9200-b4b8-11eb-859a-a194c762f47b.png)

        child: Row(
          children: [
            Flexible(
              child: FormBuilderTextField(
                name: controlId,

                decoration: InputDecoration(
                  labelText: field.dataType,
                ),

                validator: FormBuilderValidators.compose([
                  FormBuilderValidators.required(ctx),
                ]),
                initialValue: field.initialValue,

                keyboardType: TextInputType.text,
              ),
            ),
            //const VerticalDivider(),
            InkWell(
              onTap: () {
                _formKey.currentState!.fields[field.fieldName]!.didChange('');
                //_formKey.currentState!.fields[field.fieldName]!.didChange(null);
              },
              child: Icon(Icons.clear),
            ),
          ],

**Comment by avdept** [comment]
Bumping on this. Would use it too

**Comment by deandreamatias** [comment]
The answer of @avdept is correct

Currently we avoid created more parameters related with `InputDecoration`. 
Instead, we will remove existent parameters on other fields like can see in this PR: #1078
