### ISSUE TITLE
FormBuilderDateTimePicker show picker on enter control (web)

### ISSUE THREAD

**Issue by webtransplatform** [flutter-form-builder-ecosystem/flutter_form_builder#808]
First of all, thank you very much for this amazing package. This helps us so much.

I develop a web-project with this package (flutter_form_builder, with the newest version 7.xx)
When the user steps within controls with pressing Tab keys, the focus is looping through the controls very nicely. But when the focus is dropping to an FormBuilderDateTimePicker, the "onShowPicker" method is executing immadiately.
Please let the users (me :)) to control this feature with a bool variable, eg: showPickerOnEnter

  Future<void> _handleFocus() async {
    if (effectiveFocusNode!.hasFocus && enabled _**&& showPickerOnEnter**_) {
      effectiveFocusNode!.unfocus();
      await onShowPicker(context, value);
    }
  }

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/new/choose)
