### ISSUE TITLE
Restore form state?

### ISSUE THREAD

**Issue by anshgwash** [flutter-form-builder-ecosystem/flutter_form_builder#816]
If I turn on "don't keep activities" on Android Dev Options, the data input by user in my form gets deleted when you switch out of the app and come back (as expected). 
- Is there any way to keep or save this data and then restore the user's input? 
- This way data isn't lost if the OS decides to get rid of the app in the background. 

I tried putting the form key in RestorableValue and use RestorationMixin but that doesn't seem to be working.

Any help or tips would be greatly appreciated...

**Comment by kingcollision** [comment]
Love this question. The ability to save and restore form answers would be immensely useful for my users.

I tried doing something similar with initialValue but you'd have to restart the entire app. I would like something that refreshes the state of the form or initializes with values from data stored on disk. 

Anyone else have any thoughts or suggestions?

**Comment by deandreamatias** [comment]
Your state management can be restore the data and set by patch value, maybe? I don't know, a suggestion

**Comment by deandreamatias** [comment]
With the last updates of Flutter, this still a issue?
