### ISSUE TITLE
requestFocus doesn't work on FormBuilderTextField if reset is called

### ISSUE THREAD

**Issue by wyxcoder** [flutter-form-builder-ecosystem/flutter_form_builder#817]
I use text field with focusnode like

           new FormBuilderTextField(
            focusNode: myFocusNode,
            keyboardType: 'number',
           ...
On a button press, I call below code

              if (_formKey.currentState.saveAndValidate()) {
                   _formKey.currentState.fields[field_name].reset();
                    myFocusNode.requestFocus();
             }
The result is the cursor is still show in the text field with keyboard still up. But input doesn't go to the field. But when I comment out the reset line, the focus works fine.

Any idea?

**Comment by savandev17** [comment]
Facing same issue

**Comment by deandreamatias** [comment]
This still an issue?

**Comment by skibos** [comment]
Try override reset method, get controller and use clear();

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/new/choose)
