### ISSUE TITLE
email validator passes when email in a different language

### ISSUE THREAD

**Issue by alnah005** [flutter-form-builder-ecosystem/flutter_form_builder#824]
![image](https://user-images.githubusercontent.com/29386674/121283365-93819e00-c8a0-11eb-94a6-be4ead84478a.png)

![image](https://user-images.githubusercontent.com/29386674/121283249-6d5bfe00-c8a0-11eb-9ab9-f6b647bf1ecc.png)

**Comment by deandreamatias** [comment]
This still an issue?

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/new/choose)
