### ISSUE TITLE
FormBuilderDateTimePicker do not use alwaysUse24HourFormat property in version 6

### ISSUE THREAD

**Issue by Draxent** [flutter-form-builder-ecosystem/flutter_form_builder#826]
The property alwaysUse24HourFormat in FormBuilderDateTimePicker is not working anymore
Looking at the code I can see the property is not used at all.
In version 5 it was working, in version 6 is not.

**Comment by thglz** [comment]
I ran into same issue.
Here's a temporary workaround that worked for my app :

```dart
FormBuilderDateTimePicker(
    // ...
    // alwaysUse24HourFormat: true,
    transitionBuilder: (BuildContext context, Widget? child) {
      return MediaQuery(
        data: MediaQuery.of(context).copyWith(alwaysUse24HourFormat: true),
        child: child!,
      );
    },
  )
```
flutter_form_builder : 6.0.1
Flutter : 2.2.2

**Comment by deandreamatias** [comment]
Still a issue.
Take a look to this comment
https://github.com/danvick/flutter_form_builder/issues/861#issuecomment-943469650
