### ISSUE TITLE
Customize radio button shape and color

### ISSUE THREAD

**Issue by ayaanpathan** [flutter-form-builder-ecosystem/flutter_form_builder#828]
Hello, 
First of all, thank you so much for creating this amazing package. I just wanted to ask if there is any way to customize the radio button, set it's color and shape

**Comment by WilliamCunhaCardoso** [comment]
May you change it through material design on top of app. Does it work? please let us know

**Comment by deandreamatias** [comment]
> May you change it through material design on top of app. Does it work? please let us know

This response solve your question @ayaanpathan ?

**Comment by deandreamatias** [comment]
Due to lack of response, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/new/choose)
