### ISSUE TITLE
[ flutter_chips_input ] is not resent in versions above 5.0.0 

### ISSUE THREAD

**Issue by Shiba-Kar** [flutter-form-builder-ecosystem/flutter_form_builder#831]

**Comment by deandreamatias** [comment]
This still an issue?

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/new/choose)
