### ISSUE TITLE
What is the right way of Implementing FormBuilderChoiceChip??

### ISSUE THREAD

**Issue by rmControls** [flutter-form-builder-ecosystem/flutter_form_builder#832]
on select of particular chip I want to use the value for some calculation and display.... 
I tried to achieve it with onChanged method and it is not working, I am getting following error when I tried to implement it....

_Couldn't infer type parameter 'T'. Tried to infer 'int?' for 'T' which doesn't work: Parameter 'onChanged' declared as 'void Function(T?)?' but argument is 'void Function(Object?)'. The type 'int?' was inferred from: Parameter 'options' declared as 'List<FormBuilderFieldOption<T>>' but argument is 'List<FormBuilderFieldOption<int?>>'. Consider passing explicit type argument(s) to the generic._

```
FormBuilderChoiceChip(
              name: 'choice_chip',
              decoration: InputDecoration(
                labelText: 'Select an option',
              ),
              onChanged: (value){
                  print(value);   
              }
              options: [
                FormBuilderFieldOption(
                    value: 'Test', child: Text('Test')),
                FormBuilderFieldOption(
                    value: 'Test 1', child: Text('Test 1')),
                FormBuilderFieldOption(
                    value: 'Test 2', child: Text('Test 2')),
                FormBuilderFieldOption(
                    value: 'Test 3', child: Text('Test 3')),
                FormBuilderFieldOption(
                    value: 'Test 4', child: Text('Test 4')),
              ],
            )
```

Please suggest how to get selected chip value...

**Comment by ShadyZekry** [comment]
Hi @rmControls ,

I just tried your code-snippet, and everything is working fine on package version`6.0.1`.
Please, provide which version of the package that you are using,
and provide the code you want to implement and is failing.

**Comment by rmControls** [comment]
I am also using version 6.0.1...  
flutter version 2.2.2
android studio 4.1.0

**Comment by deandreamatias** [comment]
This still an issue?
