### ISSUE TITLE
How can i change the label color of FormBuilderSearchableDropdown?

### ISSUE THREAD

**Issue by Sathish9222** [flutter-form-builder-ecosystem/flutter_form_builder#836]
How can i change the label color of FormBuilderSearchableDropdown? 

Any Sample please

**Comment by deandreamatias** [comment]
Due to lack of response, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/new/choose)
