### ISSUE TITLE
Form error on hot reload

### ISSUE THREAD

**Issue by pasblin** [flutter-form-builder-ecosystem/flutter_form_builder#841]
`The following assertion was thrown building Form-[LabeledGlobalKey<FormState>#2efbc](state: FormState#83b93):
'package:flutter/src/widgets/will_pop_scope.dart': Failed assertion: line 135 pos 12: '_route == ModalRoute.of(context)': is not true.`

**Comment by deandreamatias** [comment]
This still an issue?

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/new/choose)
