### ISSUE TITLE
Flutter dropdownbutton error

### ISSUE THREAD

**Issue by ranjansigdel** [flutter-form-builder-ecosystem/flutter_form_builder#853]
DropdownButton<String>(value: selectColor,
                       onChanged: (String? selected) =>
                       setState((){
                        selectColor = selected!;
                       }),
                      items: colorList.map((String item) =>
                       DropdownMenuItem<String>(
                       value: item, child: Text(item),
                       )).toList()
                      ),

Error after choosing one item from the dropdown:

There should be exactly one item with [DropdownButton]'s value: Green. Either zero or 2 or more [DropdownMenuItem]s were detected with the same value 'package:flutter/src/material/dropdown.dart': Failed assertion: line 850 pos 15: 'items == null || items.isEmpty || value == null || items.where((DropdownMenuItem item) { return item.value == value; }).length == 1'

*selectColor is initialized with String 'Green'

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/new/choose)
