### ISSUE TITLE
Removed ImagePicker and PhoneField

### ISSUE THREAD

**Issue by dean-pearce** [flutter-form-builder-ecosystem/flutter_form_builder#855]
You removed FormBuilderImagePicker and FormBuilderPhoneField for no reason, and this ruined all of my applications that used them after upgrading the dependencies.

Even your "external" pubs for them are out of date so there is no way to use them again.
(https://pub.dev/packages/form_builder_image_picker, https://pub.dev/packages/form_builder_phone_field)

I might just drop this whole Form builder because of this "upgrade"

**Comment by deandreamatias** [comment]
@dean-pearce Maybe [this discussion](https://github.com/danvick/flutter_form_builder/discussions/1038) can be interesting to you
