### ISSUE TITLE
[FormBuilderDateTimePicker] Not reset value when form reset is called

### ISSUE THREAD

**Issue by VickyBOSS** [flutter-form-builder-ecosystem/flutter_form_builder#859]
```
formKey.currentState!.reset();
```

This behaviour can be achieved via setting the value null of DateTime field manually

`formKey.currentState!.fields["organizedOn"]?.didChange(null);`

**Comment by deandreamatias** [comment]
This still an issue?

**Comment by tonypottera24** [comment]
The reset button on the right-hand side of the `FormBuilderDateTimePicker` also doesn't work.
The `onReset` callback is not triggered.

**Comment by tonypottera24** [comment]
I saw `FormBuilderDropdown` has an `allowClear` property.
When the reset button of `FormBuilderDropdown` is pressed, the `hint` is shown.

In `FormBuilderDateTimePicker`, we have the `hintText` in `decoration`, but it will never shown.

```
FormBuilderDateTimePicker(
        name:'name',
        inputType: InputType.date,
        initialDate: DateTime.now(),
        firstDate: DateTime(1900, 1, 1),
        lastDate: DateTime.now(),
        decoration: InputDecoration(
          labelText: title,
          hintText: hint,
        ),
        onChanged: (v){},
      ),
```

```
FormBuilderDropdown(
        name:'name',
        decoration: InputDecoration(
          labelText: title,
        ),
        // initialValue: 'Male',
        allowClear: true,
        hint: hint == null ? null : Text(hint!),
        items: [
          DropdownMenuItem(
            value: 1,
            child: Text('1'),
          ),
        ],
        onChanged: (v){},
      ),
```

**Comment by deandreamatias** [comment]
The initial issue reported by @VickyBOSS, currently works successful.
In this video can see the behavior

https://user-images.githubusercontent.com/21011641/181862851-3b7b64c8-7812-43a8-b97b-4ccf6b197b01.mp4

I close this issue

**Comment by henry-ht** [comment]
I'm a little late, but I discovered that the documentation is somewhat outdated. with the following change suffixIcon will work.

![image](https://user-images.githubusercontent.com/15837863/184550137-89c11d1f-679c-4aca-9241-8bff17fa2937.png)
