### ISSUE TITLE
FormBuilderDateTimePicker issue with 24hour format and keyboard input

### ISSUE THREAD

**Issue by marko-mlinarevic** [flutter-form-builder-ecosystem/flutter_form_builder#861]
When using time picker, first jumps out wheel selector but if i go to keyboard input and enter number 10 and click done it turns it into 22 h.  Did anyone had this problem

Edit: Exact problem is this if i have always 24hours and initial entry TimePickerEntryMode.input if i enter 14 it throws an error not valid time I found a workaround in this issue https://github.com/flutter/flutter/issues/74018

now it only needs to be implemented to package
```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: GestureDetector(
            onTap: () async {
              TimeOfDay picked = await showTimePicker(
                context: context,
                initialTime: TimeOfDay.now(),
                builder: (BuildContext context, Widget child) {
                  return MediaQuery(
                    data: MediaQuery.of(context)
                        .copyWith(alwaysUse24HourFormat: true),
                    child: child,
                  );
                },);
            },
            child: Text("SetTime",textAlign: TextAlign.center,))
      ),
    );
  }


```

@danvick

**Comment by devkirch** [comment]
@marko-mlinarevic Have you found a solution? This issue still active. I have tried your Solution but it does not seem to work.

**Comment by deandreamatias** [comment]
Property `alwaysUse24HourFormat` in `FormBuilderDateTimePicker` is useless, because `FormBuilderDateTimePicker` dont use in any part of widget implementation.

**Comment by Jjagg** [comment]
For a workaround that respects the locale use the following:

```dart
final MediaQueryData media = MediaQuery.of(context);
final TimeOfDayFormat timeOfDayFormat = MaterialLocalizations.of(context).timeOfDayFormat(alwaysUse24HourFormat: media.alwaysUse24HourFormat);
final bool use24Hours = hourFormat(of: timeOfDayFormat) != HourFormat.h;

return MediaQuery(
  data: MediaQuery.of(context)
    .copyWith(alwaysUse24HourFormat: use24Hours),
  child: child, // Time picker should be created with a descendant context.
);
```

See flutter/flutter#83707 for details.
