### ISSUE TITLE
add "toggleable" option for radio group

### ISSUE THREAD

**Issue by evanholt1** [flutter-form-builder-ecosystem/flutter_form_builder#871]
as of now, _**FormBuilderRadioGroup**_ does **not** have the option available in flutter for "Radio" widget called "_**toggleable**_".
there are some use cases when selection from a radio group is "_**optional**_", i.e: you can select none, or a max of 1.
yet with this package this cannot be done and workarounds have to be followed for something already available in flutter itself. 
  I hope for the addition of a "**_toggleable_**" option for FormBuilderRadioGroup.

**Comment by deandreamatias** [comment]
Radio buttons [by design](https://uxplanet.org/radio-buttons-ux-design-588e5c0a50dc), can't be toggleable. Maybe you can use FormBuilderCheckboxGroup

**Comment by deandreamatias** [comment]
Due to lack of response, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/new/choose)

**Comment by qomhmd** [comment]
> Radio buttons [by design](https://uxplanet.org/radio-buttons-ux-design-588e5c0a50dc), can't be toggleable. Maybe you can use FormBuilderCheckboxGroup. If this solve your request, can close this issue please

https://api.flutter.dev/flutter/material/Radio/toggleable.html

**Comment by deandreamatias** [comment]
@qomhmd if do you want add the property toggleable to FormBuilderRadioGroup, I will review and merge the PR
