### ISSUE TITLE
'package:flutter_form_builder/src/form_builder.dart': Failed assertion: line 135 pos 12: '_fields.containsKey(name)': is not true.

### ISSUE THREAD

**Issue by YouSour** [flutter-form-builder-ecosystem/flutter_form_builder#875]
hi, can you show me what is problem here ? i keep get this error , thank in advance
`'package:flutter_form_builder/src/form_builder.dart': Failed assertion: line 135 pos 12: '_fields.containsKey(name)': is not true.`

**Comment by deandreamatias** [comment]
This still an issue? If yes, please add more details
