### ISSUE TITLE
FormBuilderTypeAhead.dispose() should not unconditionally dispose _typeAheadController

### ISSUE THREAD

**Issue by davebound** [flutter-form-builder-ecosystem/flutter_form_builder#910]
_FormBuilderTypeAheadState.initState() assigns _typeAheadController  to widget.controller if one was passed in:

```@override
  void initState() {
    super.initState();
    _typeAheadController = widget.controller ??
        TextEditingController(text: _getTextString(initialValue));
    // _typeAheadController.addListener(_handleControllerChanged);
  }
```

But dispose() disposes it unconditionally (despite what the comment says!)

```@override
  void dispose() {
    // Dispose the _typeAheadController when initState created it
    super.dispose();
    _typeAheadController.dispose();
  }
```

**Comment by ShadyZekry** [comment]
Hi, @davebound,

The private object `_typeAheadController` is a late non-nullable object. If the `widget.controller` has null value then `_typeAheadController` will be assigned a new instance: 
```dart
_typeAheadController =
        widget.controller
        ?? TextEditingController(text: _getTextString(initialValue));
```
Don't worry about unconditinal disposing of `_typeAheadController`, it's not nullable, Whether you have passed a controller or not, an instance will be assigned to the object.
