### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Dalio** [flutter-form-builder-ecosystem/flutter_form_builder#915]
_AssertionError ('package:form_builder_extra_fields/src/fields/form_builder_typeahead.dart': Failed assertion: line 305 pos 16: 'T == String || selectionToTextTransformer != null': is not true.)

**Comment by deandreamatias** [comment]
This still an issue?

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/new/choose)
