### ISSUE TITLE
FormBuilder currentstate disabled not effecting the color for some input components

### ISSUE THREAD

**Issue by nitojose** [flutter-form-builder-ecosystem/flutter_form_builder#925]
When a FormBuilder's currentstate is disabled, the color for FormBuilderTextField and FormBuilderDateTimePicker text values are not changed according to settings at ThemeData.disabledColor. At the same time, the color for some other components like FormBuilderRadioGroup and FormBuilderDropdown worked. Seems like this is a bug.

**Comment by deandreamatias** [comment]
This still a issue? Maybe is related with new change on Material theme properties

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/new/choose)

**Comment by vishalpatel1327** [comment]
yes having the same issue , and i verify brother thats bug
