### ISSUE TITLE
FormBuilderSlider division by 20 gives 55.00000000000001 instead of 55

### ISSUE THREAD

**Issue by Najib90** [flutter-form-builder-ecosystem/flutter_form_builder#936]
As the title says, the `FormBuilderSlider` widget gives a really long float back when using `divisions: 20` whereas I would expect it to be just 55.

```
FormBuilderSlider(
    name: text,
    initialValue: 0.0,
    divisions: 20,
    onChanged: (value) {
      _formKey.currentState?.save;
      print(_formKey.currentState?.fields[text]?.value);
    },
    min: 0,
    max: 100,
  ),
```

Screenshot:

![Screenshot 2022-01-09 at 20 30 57](https://user-images.githubusercontent.com/56278665/148697723-5e8d03dc-971d-4811-883e-576afc02c85c.png)

**Comment by deandreamatias** [comment]
This is a error on Slider widget. Can see more in this issue https://github.com/flutter/flutter/issues/39510.
When Flutter solve this error and release this fix, we update to this Flutter version

A workaround, can be use a round value when read
