### ISSUE TITLE
Disable RequestFocus when calling invalidateField

### ISSUE THREAD

**Issue by jorik** [flutter-form-builder-ecosystem/flutter_form_builder#955]
In my code I'm calling invalidateField on each field because the validation logic happens in the backend. I would like to hide the keyboard when doing this, but the invalidateField method always requests focus when called:

https://github.com/danvick/flutter_form_builder/blob/a582442f1e6bffc2fc8c4503585d03ea551c7973/packages/flutter_form_builder/lib/src/form_builder_field.dart#L228:L237

```
  void requestFocus() {
    FocusScope.of(context).requestFocus(effectiveFocusNode);
    Scrollable.ensureVisible(context);
  }

  void invalidate(String errorText) {
    setState(() => _customErrorText = errorText);
    validate(clearCustomError: false);
    requestFocus();
  }
  ```

Is it possible to disable or circumvent this behaviour?

**Comment by mdeandrea-mrmilu** [comment]
This is useful in another context.
When you need invalidate a field but has set the autovalidationMode to `AutovalidateMode.onUserInteraction`

Example:

1. Has a email field with validation Required and Email, and Form with `autovalidationMode: AutovalidateMode.onUserInteraction`
2. Write a valid email into email field
3. Call `formKey.currentState?.fields[email].invalidate(errorText: 'test')`
4. Inside `invalidate`, calls `requestFocus`
5. When focus go to email field, autovalidate is activated and validate the email
6. Show a red line above email field but don't show the text error

**Comment by DrGilion** [comment]
Hi, I'm currently working on a solution to it, because I also need that feature.
PR is coming soon :)
