### ISSUE TITLE
skipDisabled doesn't really skip

### ISSUE THREAD

**Issue by dedonnodev** [flutter-form-builder-ecosystem/flutter_form_builder#957]
Hi there,
I am using the package for my own project, and is gorgeous and super easy and fast, but I have a problem.

When I set "skipDisabled" in the form, I expect it to skip the disabled fields from validation, but it doesn't really do that.
So much so that if a field is disabled but it is "required", the validation fails.

Did I misunderstand the meaning of "skipDisabled" or is there another way to validate only "enabled" fields?

thanks.

**Comment by rifaljhonatan1** [comment]
Environment
Package version:
flutter_form_builder: ^7.7.0

yes, I also get same problem.
how to fix this..? thanks

**Comment by hellohejinyu** [comment]
<img width="784" alt="image" src="https://user-images.githubusercontent.com/8766034/202841391-8c05c86c-a201-41a2-9e8c-fd4c4a905b0e.png">

I also encountered this bug, I achieved it indirectly using a dynamic validator
