### ISSUE TITLE
Auto-filling through a password manager ?

### ISSUE THREAD

**Issue by Sandai64** [flutter-form-builder-ecosystem/flutter_form_builder#962]
Hello, I am new to Flutter and as such, I have difficulties getting auto-filling through a password manager to work on a simple login page.

My page currently looks like this :

```
FormBuilder
(
    key: _loginFormKey,
    child: AutofillGroup
    (
        key: _loginFormKey,
        child: Column
        (
            children:
            [
                FormBuilderTextField
                (
                    name: 'field1',
                    keyboardType: TextInputType.emailAddress,
                    autofillHints: const <String>[AutofillHints.username],
                ),

                FormBuilderTextField
                (
                    name: 'field2',
                    keyboardType: TextInputType.visiblePassword,
                    autofillHints: const <String>[AutofillHints.password],
                    obscureText: true,
                ),
            ],
        ) // Column
    ) // AutoFillGroup
), // FormBuilder
```
Is there some property I missed that is causing auto-fill not to work or is the feature missing from the package ? Should I implement this using a Flutter form from scratch ?

For my tests I used Bitwarden, it was only capable of filling the username field and not the password.

If you have any more questions, please ask.

**Comment by WilliamCunhaCardoso** [comment]
Good question. Actually, I would have to search which `Flutter` component support such feature.

**Comment by FrazeColder** [comment]
Any updates here? I have the same problem and I don't think @erwangse and me are the only two people who need this feature.

**Comment by AlBlanc** [comment]
Hello, 

I am a little bit late, thank you for the issue. I investigated a little bit and it looks like we need to proxy the autofill parameter to Textfields -> https://api.flutter.dev/flutter/widgets/AutofillGroup-class.html

**Comment by AlBlanc** [comment]
After looking at the code, it seems you can already pass an `autofillHints` parameter to the `FormBuilderTextField`. Please have a look at [this documentation](https://api.flutter.dev/flutter/services/AutofillHints-class.html) to find the proper values.

In case of several `FormBuilderTextField`(s), do not forget to wrap them with an [`AutofillGroup`](https://api.flutter.dev/flutter/widgets/AutofillGroup-class.html)
