### ISSUE TITLE
Field replacement logic

### ISSUE THREAD

**Issue by Marcosmaliki** [flutter-form-builder-ecosystem/flutter_form_builder#963]
In the changelog for version 7.1.0, we have this bullet _**Improved field replacement logic**_
How has this been improved?

**Case**
If I have a form with a radio button which displays/hides other fields depending on selection

**Expected result**
I expect to only get a Map of what was drawn on the screen when I run` formkey.currentState?.save()`

**Actual result**
What I get is a Map with all the fields ever drawn on the screen, whether hidden or not. 
Validation still works as expected, hidden fields will not be validated which is exactly what I want.

**Comment by Marcosmaliki** [comment]
I might have found a workaround by using  `c.formKey.currentState?.removeInternalFieldValue('fieldName',isSetState: false);`

**Comment by deandreamatias** [comment]
@Marcosmaliki  You can disable your hidden fields and set `skipDisabled` on `FormBuilder`. 
If this is enough for you, please close this issue
