### ISSUE TITLE
An Exception caught by widgets library occurs while typing in FormBuilderTextField

### ISSUE THREAD

**Issue by Uvais-Mohammad** [flutter-form-builder-ecosystem/flutter_form_builder#966]
An Exception caught by widgets library is occurring while typing something in FormBuilderTextField. Please let me know if there is any solution

Code is given below:
```
 body: FormBuilder(
        key: _formKey,
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Column(
            children: [
              const SizedBox(height: 8),
              FormBuilderTextField(
                name: 'universityName',
                decoration: InputDecoration(
                  labelText:  'University Name' ),
                validator: FormBuilderValidators.required(context),
              ),
           ],
          ),
        ),
      ), 
```

![image](https://user-images.githubusercontent.com/63300484/154078348-8dbff23d-b286-4443-b41a-591524149c5d.png)

**Comment by deandreamatias** [comment]
@Uvais-Mohammad This still an issue?
Seems that this is related to combination with ancestor widget.
Has the complete example to test?

**Comment by Uvais-Mohammad** [comment]
The problem was related to ancestor widget. It is fixed
