### ISSUE TITLE
Disable editing the whole form at once.

### ISSUE THREAD

**Issue by pragatisha** [flutter-form-builder-ecosystem/flutter_form_builder#984]
Is there any way we can do this. cancel submission/editing of a form in certain state.

**Comment by WilliamCunhaCardoso** [comment]
Could you give more details?

**Comment by pragatisha** [comment]
Disable editing all fields that is in the form to prevent the user to change it. It can be used when the form is submitted and the user won't be allowed to change the form values after submitting.

**Comment by danvick** [comment]
Setting `enabled: false` on the form should work, does it not?

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/new/choose)
